In [161]:
import numpy as np
import pandas as pd

### <p style="background-color:#78BAF0;color:black;font-size:25px;text-align:center;border-radius:35px 35px;border-style:solid;border-color:blue;">🔏Mô tả dữ liệu </p>


<br>1. Tiêu đề: TIỀN XỬ LÝ DỮ LIỆU 
<br>2. Nguồn: CUỘC THI DATA GOT TALENT.
<br>3. Kích thước: Gồm 4 sheet chính ( 1 sheet là readme, 3 sheet bao gồm bảng customer, bảng tickets và bảng films)
<br>4. Thông tin bảng :
- customer: Thông tin về khách hàng , bao gồm 7 cột (customerid, DOB, Gender, address, Website, Job, Industry) và 4480 dòng
- tickets : Thông tin về giao dịch vé , bao gôm 15 cột(customerid, orderid, saledate, ticketprice ,... ) và 35475 dòng
- films : Thông tin về phim , bao gồm 10 cột ( title,director,country,...) và 61 dòng

### <p style="background-color:#78BAF0;color:black;font-size:25px;text-align:center;border-radius:35px 35px;border-style:solid;border-color:blue;">✨ Nội dung chính </p>
1. Thực hiện tiền xử lý với bảng customer
  - 1.1. Hàm chuyển đổi giá trị chuẩn hóa excel thành dạng dữ liệu năm/tháng/ngày ở cột DOB
  - 1.2. Tạo cột mới tên Tuổi xem phim bằng việc lấy (tháng5/2019) - dữ liệu của cột DOB sau khi đã chuẩn hóa
  - 1.3. Gán các missing value ở cột industry thành giá trị "NoJob"
  - 1.4. Gán các missing value ở cột Website thành giá trị "Không có dữ liệu"
  - 1.5. Tạo cột mới dựa trên dữ liệu của cột Website , cột mới có tên "Dữ liệu Web"
  - 1.6. Xử lý cột address và tạo ra 3 cột mới là "Đường","Quận" và "Thành Phố"
  - 1.7. Xử lý các giá trị DOB bị lỗi sau khi chuẩn hóa dữ liệu 
  - 1.8. Xóa cột Đường và xuất ra file excel
2. Thực hiện tiền xử lý với bảng tickets
  - 2.1. Làm việc với cột orderid (kiểm tra trùng, kiểm tra missing value, gán lại các giá trị missing value)
  - 2.2. Làm việc với cột cashier , nhận ra các vấn đề hoặc những điểm thú vị của cột cashier
  - 2.3. Làm việc với cột customerid , kiểm tra giá trị trùng lặp , kiểm tra null, kiểm tra format của customerid
  - 2.4. Làm việc với cột popcorn , kiểm tra các misssing value , gán các missing value thành "Website/Liên hệ tại quầy"
  - 2.5. Làm việc với cột saledate, tách cột saledate ra thành 2 cột là saledate và saletime, trong đó saledate chỉ chứa format giá trị (năm/tháng/ngày) và saletime chứa giá trị time. Gán các giá trị saledate null thành các giá trị phù hợp với dữ liệu
  - 2.6. Làm việc với cột ticket price , kiểm tra các mức giá của rạp chiếu , gán lại giá trị của ticket price bị lỗi. Nhận xét xem thử các mức giá đại diện cho vấn đề gì, sự khác nhau giữa chúng là gì.
  - 2.7. Làm việc với cột ticketcode, kiểm tra null và kiểm tra các giá trị trùng lặp , xử lý bằng việc thay thế lại các giá trị trùng lặp
  - 2.8. Làm việc với cột saletime , gán lại các missing value cho cột saletime là "Không xác định rõ"
  - 2.9. Làm việc với cột total , gán lại các missing value của cột total đúng với format của dataset, gán lại các giá trị total bị sai sót do việc ticket price bị sai 
  - 2.10. Tạo cột mới "Cách thức mua vé" có 2 giá trị unique là "Online" và "Offline"
  - 2.11. Xuất ra file excel

In [162]:
excel_file = 'DATA SET - VÒNG 1 CUỘC THI DATA GOT TALENT 2023.xlsx'
sheets = ['customer', 'ticket','film']

# Làm việc với bảng customer

## Đọc dữ liệu 

In [163]:
customer = pd.read_excel(excel_file, sheet_name='customer')

In [164]:
customer.shape

(4479, 7)

In [165]:
customer.head()

customerid    DOB gender                 address       Website  \
0  0000000014  36268     Nữ  hoa khe quan thanh khe   KH0104|0345   
1  0000000034  35901    Nam                man thai   KH0104|0333   
2  0000000051  34319    Nam       que son quang nam   KH0104|0255   
3  0000000081  36472    Nam            truong chinh   KH0104|0293   
4  0000000098  34608    Nam                  cẩm lệ  KH0104|40580   

           job        industry  
0      student        computer  
1      student  health service  
2  blue collar       economics  
3      student       economics  
4  blue collar  health service

In [166]:
customer.tail()

customerid    DOB gender                           address  \
4474        KH9855766  34885     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG   
4475        KH9958204  36892     Nữ                      Phước Mỹ, ĐN   
4476  WEBS00000043900  32311     Nữ                 nguyen gian thanh   
4477  WEBS00000044909  35316     Nữ                      ngũ hành sơn   
4478  WEBS00000046015  37372     Nữ         Thanh Khê Tây - Thanh Khê   

              Website          job      industry  
4474              NaN   specialist       finance  
4475              NaN     teenager           NaN  
4476  KHWEBS|00006890   specialist  construction  
4477  KHWEBS|00007899  blue collar       finance  
4478  KHWEBS|00009005     teenager           NaN

## Làm việc với cột customerid

In [167]:
print(customer["customerid"].dtype)

object


In [168]:
import re
def clean_custid(id):
    return re.sub(r'([.,!?;-]+)$', '', id)

customer['customerid'] = customer['customerid'].apply(clean_custid)



## Làm việc với cột DOB

In [169]:
print(customer["DOB"].dtype)

int64


In [170]:
print(customer["DOB"].isnull().any())
# Không có null

False


In [171]:
from datetime import datetime, timedelta

def convert_excel_date(excel_date_value):
    excel_start_date = datetime(1899, 12, 30) 
    corresponding_date = excel_start_date + timedelta(days=excel_date_value)
    return corresponding_date

excel_date_value = 36268 
date = convert_excel_date(excel_date_value)

# Áp dụng hàm chuyển đổi lên cột 'DOB'
customer['DOB'] = customer['DOB'].apply(convert_excel_date)

# Định dạng lại ngày tháng nếu cần và kiểm tra lại kiểu dữ liệu
customer['DOB'] = customer['DOB'].apply(lambda x: x.strftime("%Y-%m-%d") if isinstance(x, datetime) else x)

# Hiển thị DataFrame sau khi đã thay đổi
customer

customerid         DOB gender                           address  \
0          0000000014  1999-04-18     Nữ            hoa khe quan thanh khe   
1          0000000034  1998-04-16    Nam                          man thai   
2          0000000051  1993-12-16    Nam                 que son quang nam   
3          0000000081  1999-11-08    Nam                      truong chinh   
4          0000000098  1994-10-01    Nam                            cẩm lệ   
...               ...         ...    ...                               ...   
4474        KH9855766  1995-07-05     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG   
4475        KH9958204  2001-01-01     Nữ                      Phước Mỹ, ĐN   
4476  WEBS00000043900  1988-06-17     Nữ                 nguyen gian thanh   
4477  WEBS00000044909  1996-09-08     Nữ                      ngũ hành sơn   
4478  WEBS00000046015  2002-04-26     Nữ         Thanh Khê Tây - Thanh Khê   

              Website          job        industry  
0         KH0104|0345      student        computer  
1         KH0104|0333      student  health service  
2         KH0104|0255  blue collar       economics  
3         KH0104|0293      student       economics  
4        KH0104|40580  blue collar  health service  
...               ...          ...             ...  
4474              NaN   specialist         finance  
4475              NaN     teenager             NaN  
4476  KHWEBS|00006890   specialist    construction  
4477  KHWEBS|00007899  blue collar         finance  
4478  KHWEBS|00009005     teenager             NaN  

[4479 rows x 7 columns]

In [172]:
# Convert 'DOB' to datetime
customer['DOB'] = pd.to_datetime(customer['DOB'], errors='coerce')

# Define the date for May 2019
may_2019 = datetime(2019, 5, 1)

# Calculate the new column 'Tuổi xem phim' as the difference in years
customer['Tuổi xem phim'] = customer['DOB'].apply(lambda x: (may_2019 - x).days // 365 if pd.notnull(x) else None)

# Display the DataFrame to verify the new column
customer

customerid        DOB gender                           address  \
0          0000000014 1999-04-18     Nữ            hoa khe quan thanh khe   
1          0000000034 1998-04-16    Nam                          man thai   
2          0000000051 1993-12-16    Nam                 que son quang nam   
3          0000000081 1999-11-08    Nam                      truong chinh   
4          0000000098 1994-10-01    Nam                            cẩm lệ   
...               ...        ...    ...                               ...   
4474        KH9855766 1995-07-05     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG   
4475        KH9958204 2001-01-01     Nữ                      Phước Mỹ, ĐN   
4476  WEBS00000043900 1988-06-17     Nữ                 nguyen gian thanh   
4477  WEBS00000044909 1996-09-08     Nữ                      ngũ hành sơn   
4478  WEBS00000046015 2002-04-26     Nữ         Thanh Khê Tây - Thanh Khê   

              Website          job        industry  Tuổi xem phim  
0         KH0104|0345      student        computer           20.0  
1         KH0104|0333      student  health service           21.0  
2         KH0104|0255  blue collar       economics           25.0  
3         KH0104|0293      student       economics           19.0  
4        KH0104|40580  blue collar  health service           24.0  
...               ...          ...             ...            ...  
4474              NaN   specialist         finance           23.0  
4475              NaN     teenager             NaN           18.0  
4476  KHWEBS|00006890   specialist    construction           30.0  
4477  KHWEBS|00007899  blue collar         finance           22.0  
4478  KHWEBS|00009005     teenager             NaN           17.0  

[4479 rows x 8 columns]

In [173]:
df1_dtype_before = customer['Tuổi xem phim'].dtype

# Convert 'Tuổi xem phim' to integer
customer['Tuổi xem phim'] = customer['Tuổi xem phim'].astype('Int64')  # Using 'Int64' to handle NaN values

# Check the data type after conversion
customer_dtype_after = customer['Tuổi xem phim'].dtype


In [174]:
customer

customerid        DOB gender                           address  \
0          0000000014 1999-04-18     Nữ            hoa khe quan thanh khe   
1          0000000034 1998-04-16    Nam                          man thai   
2          0000000051 1993-12-16    Nam                 que son quang nam   
3          0000000081 1999-11-08    Nam                      truong chinh   
4          0000000098 1994-10-01    Nam                            cẩm lệ   
...               ...        ...    ...                               ...   
4474        KH9855766 1995-07-05     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG   
4475        KH9958204 2001-01-01     Nữ                      Phước Mỹ, ĐN   
4476  WEBS00000043900 1988-06-17     Nữ                 nguyen gian thanh   
4477  WEBS00000044909 1996-09-08     Nữ                      ngũ hành sơn   
4478  WEBS00000046015 2002-04-26     Nữ         Thanh Khê Tây - Thanh Khê   

              Website          job        industry  Tuổi xem phim  
0         KH0104|0345      student        computer             20  
1         KH0104|0333      student  health service             21  
2         KH0104|0255  blue collar       economics             25  
3         KH0104|0293      student       economics             19  
4        KH0104|40580  blue collar  health service             24  
...               ...          ...             ...            ...  
4474              NaN   specialist         finance             23  
4475              NaN     teenager             NaN             18  
4476  KHWEBS|00006890   specialist    construction             30  
4477  KHWEBS|00007899  blue collar         finance             22  
4478  KHWEBS|00009005     teenager             NaN             17  

[4479 rows x 8 columns]

## Làm việc với cột industry

In [175]:
industries = customer['industry'].unique()
print(industries)

['computer' 'health service' 'economics' 'education' 'construction'
 'social service' 'government agent' nan 'finance' 'engineering']


In [176]:
industries_null = customer[customer['industry'].isnull()]
industries_null

customerid        DOB gender                    address  \
16         0000000384 2002-11-22     Nữ                 liên chiểu   
17         0000000385 2002-12-02     Nữ                   hòa vang   
20         0000000509 2002-10-28     Nữ            Phan Dinh Phung   
23         0000000576 2016-01-11    Nam                    sơn trà   
32         0000000765 2000-09-21     Nữ              Dien Bien Phu   
...               ...        ...    ...                        ...   
4468        KH9743341 2000-02-25    Nam                  Nui Thanh   
4471        KH9830912 2000-03-07     Nữ        ĐIỆN BÀN, QUẢNG NAM   
4473         KH984255 2000-05-04    Nam          Hai Chau, Da Nang   
4475        KH9958204 2001-01-01     Nữ               Phước Mỹ, ĐN   
4478  WEBS00000046015 2002-04-26     Nữ  Thanh Khê Tây - Thanh Khê   

              Website       job industry  Tuổi xem phim  
16       KH0104|19665  teenager      NaN             16  
17       KH0104|20328  teenager      NaN             16  
20        KH0104|0430  teenager      NaN             16  
23        KH0104|0519  teenager      NaN              3  
32        KH0104|0047  teenager      NaN             18  
...               ...       ...      ...            ...  
4468              NaN  teenager      NaN             19  
4471              NaN  teenager      NaN             19  
4473              NaN  teenager      NaN             19  
4475              NaN  teenager      NaN             18  
4478  KHWEBS|00009005  teenager      NaN             17  

[1122 rows x 8 columns]

In [177]:
df5 = customer[customer['industry'].isnull()]

# Lấy ra cột job cho df đã lọc 
jobs = df5['job']

# Kiểm tra các giá trị trong cột job
print(jobs.unique()) 
print(jobs.value_counts())

['teenager']
job
teenager    1122
Name: count, dtype: int64


### Gán giá trị null tương ứng với cột industry là cột Nojob

In [178]:
NEW_VALUE = 'NoJob'

customer.loc[(customer['industry'].isnull()) & (customer['job'] == 'teenager'), 'industry'] = NEW_VALUE

In [179]:
teen_df = customer[customer['job'] == 'teenager']
teen_df

customerid        DOB gender                    address  \
16         0000000384 2002-11-22     Nữ                 liên chiểu   
17         0000000385 2002-12-02     Nữ                   hòa vang   
20         0000000509 2002-10-28     Nữ            Phan Dinh Phung   
23         0000000576 2016-01-11    Nam                    sơn trà   
32         0000000765 2000-09-21     Nữ              Dien Bien Phu   
...               ...        ...    ...                        ...   
4468        KH9743341 2000-02-25    Nam                  Nui Thanh   
4471        KH9830912 2000-03-07     Nữ        ĐIỆN BÀN, QUẢNG NAM   
4473         KH984255 2000-05-04    Nam          Hai Chau, Da Nang   
4475        KH9958204 2001-01-01     Nữ               Phước Mỹ, ĐN   
4478  WEBS00000046015 2002-04-26     Nữ  Thanh Khê Tây - Thanh Khê   

              Website       job industry  Tuổi xem phim  
16       KH0104|19665  teenager    NoJob             16  
17       KH0104|20328  teenager    NoJob             16  
20        KH0104|0430  teenager    NoJob             16  
23        KH0104|0519  teenager    NoJob              3  
32        KH0104|0047  teenager    NoJob             18  
...               ...       ...      ...            ...  
4468              NaN  teenager    NoJob             19  
4471              NaN  teenager    NoJob             19  
4473              NaN  teenager    NoJob             19  
4475              NaN  teenager    NoJob             18  
4478  KHWEBS|00009005  teenager    NoJob             17  

[1122 rows x 8 columns]

## Làm việc với cột Website

In [180]:
print(customer["Website"].dtype)

object


In [181]:
print(customer["Website"].isnull().any())

True


=>> Có null ở cột Website

In [182]:
customer_web = customer[customer['Website'].isnull()]
customer_web

customerid        DOB gender                           address Website  \
7     0000000228 1995-11-09    Nam                  Ngũ Hành Sơn, ĐN     NaN   
14    0000000328 1994-03-28    Nam                      Le Tan Trung     NaN   
33    0000000777 1994-12-07     Nữ                         THANH KHÊ     NaN   
49    0000003225 1992-01-01    Nam                      ngũ hành sơn     NaN   
57    0000003363 1997-04-10    Nam                           ĐỐNG ĐA     NaN   
...          ...        ...    ...                               ...     ...   
4471   KH9830912 2000-03-07     Nữ               ĐIỆN BÀN, QUẢNG NAM     NaN   
4472   KH9834570 1997-01-11    Nam             Ngu Hanh Son, Da Nang     NaN   
4473    KH984255 2000-05-04    Nam                 Hai Chau, Da Nang     NaN   
4474   KH9855766 1995-07-05     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG     NaN   
4475   KH9958204 2001-01-01     Nữ                      Phước Mỹ, ĐN     NaN   

              job          industry  Tuổi xem phim  
7      specialist    health service             23  
14    blue collar         economics             25  
33     specialist         economics             24  
49    blue collar    social service             27  
57        student  government agent             22  
...           ...               ...            ...  
4471     teenager             NoJob             19  
4472      student    social service             22  
4473     teenager             NoJob             19  
4474   specialist           finance             23  
4475     teenager             NoJob             18  

[536 rows x 8 columns]

In [183]:
customer['Website'] = customer['Website'].fillna('Không có dữ liệu')
customer

customerid        DOB gender                           address  \
0          0000000014 1999-04-18     Nữ            hoa khe quan thanh khe   
1          0000000034 1998-04-16    Nam                          man thai   
2          0000000051 1993-12-16    Nam                 que son quang nam   
3          0000000081 1999-11-08    Nam                      truong chinh   
4          0000000098 1994-10-01    Nam                            cẩm lệ   
...               ...        ...    ...                               ...   
4474        KH9855766 1995-07-05     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG   
4475        KH9958204 2001-01-01     Nữ                      Phước Mỹ, ĐN   
4476  WEBS00000043900 1988-06-17     Nữ                 nguyen gian thanh   
4477  WEBS00000044909 1996-09-08     Nữ                      ngũ hành sơn   
4478  WEBS00000046015 2002-04-26     Nữ         Thanh Khê Tây - Thanh Khê   

               Website          job        industry  Tuổi xem phim  
0          KH0104|0345      student        computer             20  
1          KH0104|0333      student  health service             21  
2          KH0104|0255  blue collar       economics             25  
3          KH0104|0293      student       economics             19  
4         KH0104|40580  blue collar  health service             24  
...                ...          ...             ...            ...  
4474  Không có dữ liệu   specialist         finance             23  
4475  Không có dữ liệu     teenager           NoJob             18  
4476   KHWEBS|00006890   specialist    construction             30  
4477   KHWEBS|00007899  blue collar         finance             22  
4478   KHWEBS|00009005     teenager           NoJob             17  

[4479 rows x 8 columns]

### Tạo cột mới mang 2 giá trị dựa vào giá trị của cột Website (No Data Website và Have Data Website)

In [184]:
customer['Dữ liệu web'] = customer['Website'].apply(lambda x: 'No Data Website' if x == 'Không có dữ liệu' else 'Have Data Website')

In [185]:
customer[['Website', 'Dữ liệu web']]

Website        Dữ liệu web
0          KH0104|0345  Have Data Website
1          KH0104|0333  Have Data Website
2          KH0104|0255  Have Data Website
3          KH0104|0293  Have Data Website
4         KH0104|40580  Have Data Website
...                ...                ...
4474  Không có dữ liệu    No Data Website
4475  Không có dữ liệu    No Data Website
4476   KHWEBS|00006890  Have Data Website
4477   KHWEBS|00007899  Have Data Website
4478   KHWEBS|00009005  Have Data Website

[4479 rows x 2 columns]

In [186]:
customer

customerid        DOB gender                           address  \
0          0000000014 1999-04-18     Nữ            hoa khe quan thanh khe   
1          0000000034 1998-04-16    Nam                          man thai   
2          0000000051 1993-12-16    Nam                 que son quang nam   
3          0000000081 1999-11-08    Nam                      truong chinh   
4          0000000098 1994-10-01    Nam                            cẩm lệ   
...               ...        ...    ...                               ...   
4474        KH9855766 1995-07-05     Nữ  A, THUAN PHUOC,HAI CHAU, DA NANG   
4475        KH9958204 2001-01-01     Nữ                      Phước Mỹ, ĐN   
4476  WEBS00000043900 1988-06-17     Nữ                 nguyen gian thanh   
4477  WEBS00000044909 1996-09-08     Nữ                      ngũ hành sơn   
4478  WEBS00000046015 2002-04-26     Nữ         Thanh Khê Tây - Thanh Khê   

               Website          job        industry  Tuổi xem phim  \
0          KH0104|0345      student        computer             20   
1          KH0104|0333      student  health service             21   
2          KH0104|0255  blue collar       economics             25   
3          KH0104|0293      student       economics             19   
4         KH0104|40580  blue collar  health service             24   
...                ...          ...             ...            ...   
4474  Không có dữ liệu   specialist         finance             23   
4475  Không có dữ liệu     teenager           NoJob             18   
4476   KHWEBS|00006890   specialist    construction             30   
4477   KHWEBS|00007899  blue collar         finance             22   
4478   KHWEBS|00009005     teenager           NoJob             17   

            Dữ liệu web  
0     Have Data Website  
1     Have Data Website  
2     Have Data Website  
3     Have Data Website  
4     Have Data Website  
...                 ...  
4474    No Data Website  
4475    No Data Website  
4476  Have Data Website  
4477  Have Data Website  
4478  Have Data Website  

[4479 rows x 9 columns]

In [187]:
Website = customer['Dữ liệu web'].unique()
print(Website)

['Have Data Website' 'No Data Website']


## Làm việc với cột address

In [188]:
print(customer["address"].dtype)

object


### Xóa dấu

In [189]:
import re
import unicodedata

def remove_accents(input_str):
    nfkd_form = unicodedata.normalize('NFKD', input_str)
    return "".join([c for c in nfkd_form if not unicodedata.combining(c)])

customer['address'] = customer['address'].astype(str)
customer['address'] = customer['address'].apply(remove_accents)

### Thay dấu - thành dấu phẩy

In [190]:
# Thay thế dấu "-" với khoảng trắng trước và sau bằng dấu phẩy
customer['address'] = customer['address'].str.replace(r'\s*-\s*', ',', regex=True)

### Xóa các khoảng trắng sau dấu phẩy 

In [191]:
#Xóa khoảng trắng đầu và cuối của các giá trị trong cột 'address'.
# Đồng thời xóa khoảng trắng sau các dấu phẩy nếu có.
customer['address'] = customer['address'].str.strip().str.replace(r'\s*,\s*', ',', regex=True)

### Xóa khoảng trắng trước và sau 

In [192]:
customer['address'] = customer['address'].str.strip()

### Thay thành lowercase

In [193]:
customer['address'] = customer['address'].str.lower()

In [194]:
customer

customerid        DOB gender                         address  \
0          0000000014 1999-04-18     Nữ          hoa khe quan thanh khe   
1          0000000034 1998-04-16    Nam                        man thai   
2          0000000051 1993-12-16    Nam               que son quang nam   
3          0000000081 1999-11-08    Nam                    truong chinh   
4          0000000098 1994-10-01    Nam                          cam le   
...               ...        ...    ...                             ...   
4474        KH9855766 1995-07-05     Nữ  a,thuan phuoc,hai chau,da nang   
4475        KH9958204 2001-01-01     Nữ                     phuoc my,đn   
4476  WEBS00000043900 1988-06-17     Nữ               nguyen gian thanh   
4477  WEBS00000044909 1996-09-08     Nữ                    ngu hanh son   
4478  WEBS00000046015 2002-04-26     Nữ         thanh khe tay,thanh khe   

               Website          job        industry  Tuổi xem phim  \
0          KH0104|0345      student        computer             20   
1          KH0104|0333      student  health service             21   
2          KH0104|0255  blue collar       economics             25   
3          KH0104|0293      student       economics             19   
4         KH0104|40580  blue collar  health service             24   
...                ...          ...             ...            ...   
4474  Không có dữ liệu   specialist         finance             23   
4475  Không có dữ liệu     teenager           NoJob             18   
4476   KHWEBS|00006890   specialist    construction             30   
4477   KHWEBS|00007899  blue collar         finance             22   
4478   KHWEBS|00009005     teenager           NoJob             17   

            Dữ liệu web  
0     Have Data Website  
1     Have Data Website  
2     Have Data Website  
3     Have Data Website  
4     Have Data Website  
...                 ...  
4474    No Data Website  
4475    No Data Website  
4476  Have Data Website  
4477  Have Data Website  
4478  Have Data Website  

[4479 rows x 9 columns]

### Thay format chính để xử lý address

In [195]:
# Định nghĩa hàm để xử lý cột 'address' theo yêu cầu:
# - Nếu có nhiều hơn 2 dấu phẩy, xóa dấu phẩy ở giữa.
# - Nếu không có dấu phẩy ở vị trí cuối cùng, thêm dấu phẩy và "đà nẵng".
def process_address(address):
    # Đếm số dấu phẩy
    comma_count = address.count(',')
    
    # Xử lý trường hợp có nhiều hơn 2 dấu phẩy
    if comma_count > 2:
        # Tách chuỗi thành các phần và loại bỏ phần tử thứ hai (dấu phẩy thứ hai)
        parts = address.split(',')
        address = ','.join(parts[:2] + parts[3:])
    # Xử lý trường hợp không có dấu phẩy ở cuối
    elif comma_count < 2:
        # Thêm ",đà nẵng" vào cuối chuỗi
        address += ',đà nẵng'
        
    return address

# Áp dụng hàm đã định nghĩa lên cột 'address' của DataFrame customer
customer['address'] = customer['address'].apply(process_address)

In [196]:
def remove_danang_abbreviations(address):
    # Định nghĩa danh sách các từ viết tắt cần loại bỏ
    danang_abbreviations = ['đn', 'tp đà nẵng', 'da nang','tp. da nang',"đa nang","tp đa nang","tp.","tp"]
    
    # Kiểm tra và thay thế các từ viết tắt bằng chuỗi rỗng
    for abbr in danang_abbreviations:
        address = address.replace(abbr, '')
    
    # Loại bỏ các dấu phẩy thừa và khoảng trắng
    address_clean = ','.join([part.strip() for part in address.split(',') if part.strip()])
    
    return address_clean

# Áp dụng hàm đã định nghĩa lên cột 'address' của DataFrame customer
customer['address'] = customer['address'].apply(remove_danang_abbreviations)

In [197]:
import re

def remove_accents(input_str):
    # Bảng đổi chữ có dấu sang không dấu
    replacements = (
        ("à|á|ả|ã|ạ|ă|ằ|ắ|ẳ|ẵ|ặ|â|ầ|ấ|ẩ|ẫ|ậ", "a"),
        ("è|é|ẻ|ẽ|ẹ|ê|ề|ế|ể|ễ|ệ", "e"),
        ("ì|í|ỉ|ĩ|ị", "i"),
        ("ò|ó|ỏ|õ|ọ|ô|ồ|ố|ổ|ỗ|ộ|ơ|ờ|ớ|ở|ỡ|ợ", "o"),
        ("ù|ú|ủ|ũ|ụ|ư|ừ|ứ|ử|ữ|ự", "u"),
        ("ỳ|ý|ỷ|ỹ|ỵ", "y"),
    )
    
    for pattern, repl in replacements:
        input_str = re.sub(pattern, repl, input_str)
        
    return input_str.lower()

tinh_thanh_list = ["quang tri", "quang ngai", "hue",  
                   "quang binh", "binh dinh", "dong nai",  
                   "khanh hoa", "hai duong", "nghe an",
                   "gia lai", "kon tum", "dak lak", "ha tinh",
                   "ha noi", "tp ho chi minh", "quang nam","ho chi minh","da nang"]
                   
quan_da_nang = ["son tra", "ngu hanh son", "cam le", 
                "thanh khe", "lien chieu", "hoa vang","hai chau"]
                

def split_address(address, quan_list, tinh_thanh_list):
    address_norm = remove_accents(address)

    # Loại bỏ từ "quận" nếu có trong tên đường
    address_norm = re.sub(r'\bquan\b', '', address_norm).strip()

    # Xác định thành phố
    thanhpho = None
    for tinh_thanh in tinh_thanh_list:
        tinh_thanh_norm = remove_accents(tinh_thanh)
        if tinh_thanh_norm in address_norm:
            thanhpho = tinh_thanh
            address_norm = address_norm.replace(tinh_thanh_norm, "").strip()
            break
       # Nếu không tìm thấy trong danh sách tỉnh, mặc định là Đà Nẵng
    if not thanhpho:
        thanhpho = "đà nẵng"

    # Xác định quận và đường
    quan = None
    duong = None

    # Nếu địa chỉ không thuộc Đà Nẵng, đặt Đường là "Ngoại tỉnh"
    if thanhpho != "đà nẵng":
        quan = "ngoại tỉnh"
        duong = "ngoại tỉnh"
    else:
        # Tìm và loại bỏ tên quận từ địa chỉ chuẩn hóa
        for q in quan_list:
            q_norm = remove_accents(q)
            if q_norm in address_norm:
                quan = q
                address_norm = address_norm.replace(q_norm, "").strip()
                break
         # Loại bỏ từ "đà nẵng" nếu có trong chuỗi địa chỉ chuẩn hóa
        da_nang_norm = remove_accents(",đà nẵng")
        address_norm = address_norm.replace(da_nang_norm, "").strip()

        # Đường chỉ là phần còn lại của địa chỉ sau khi loại bỏ quận và thành phố
        # duong = address_norm
        duong = re.sub(r'^[,\s]*|[,\s]*$', '', address_norm)
    return duong, quan, thanhpho

# Áp dụng hàm
customer['Đường'], customer['Quận'], customer['Thành Phố'] = zip(*customer['address'].apply(lambda x: split_address(x, quan_da_nang, tinh_thanh_list)))

# Xem kết quả sau khi tách
customer[['address', 'Đường', 'Quận', 'Thành Phố']]

address              Đường          Quận  \
0      hoa khe quan thanh khe,đà nẵng            hoa khe     thanh khe   
1                    man thai,đà nẵng           man thai          None   
2           que son quang nam,đà nẵng         ngoại tỉnh    ngoại tỉnh   
3                truong chinh,đà nẵng       truong chinh          None   
4                      cam le,đà nẵng                           cam le   
...                               ...                ...           ...   
4474                    a,thuan phuoc      a,thuan phuoc          None   
4475                 phuoc my,đà nẵng           phuoc my          None   
4476        nguyen gian thanh,đà nẵng  nguyen gian thanh          None   
4477             ngu hanh son,đà nẵng                     ngu hanh son   
4478  thanh khe tay,thanh khe,đà nẵng                tay     thanh khe   

      Thành Phố  
0       đà nẵng  
1       đà nẵng  
2     quang nam  
3       đà nẵng  
4       đà nẵng  
...         ...  
4474    đà nẵng  
4475    đà nẵng  
4476    đà nẵng  
4477    đà nẵng  
4478    đà nẵng  

[4479 rows x 4 columns]

In [198]:
quan_mapping = {
    "son tra": "Sơn Trà",
    "ngu hanh son": "Ngũ Hành Sơn", 
    "cam le": "Cẩm Lệ",
    "thanh khe": "Thanh Khê",
    "lien chieu": "Liên Chiểu",
    "hoa vang": "Hòa Vang",
    "hai chau": "Hải Châu",
    "ngoại tỉnh":"Ngoại Tỉnh"
}

customer["Quận"] = customer["Quận"].map(quan_mapping)

In [199]:
tinh_mapping = {
    "da nang": "Đà Nẵng",  
    "đà nẵng": "Đà Nẵng",
    "quang nam": "Quảng Nam",
    "quang tri": "Quảng Trị",
    "hue": "Huế",
    "quang ngai": "Quảng Ngãi",
    "nghe an": "Nghệ An",
    "gia lai": "Gia Lai",  
    "quang binh": "Quảng Bình",
    "ha tinh": "Hà Tĩnh",
    "hai duong": "Hải Dương",
    "ha noi": "Hà Nội",
    "khanh hoa": "Khánh Hòa",
    "kon tum": "Kon Tum",
    "dak lak": "Đắk Lắk",
    "ho chi minh": "Hồ Chí Minh"
    
}

customer["Thành Phố"] = customer["Thành Phố"].map(tinh_mapping)

In [200]:
customer[['address', 'Đường', 'Quận', 'Thành Phố']]

address              Đường          Quận  \
0      hoa khe quan thanh khe,đà nẵng            hoa khe     Thanh Khê   
1                    man thai,đà nẵng           man thai           NaN   
2           que son quang nam,đà nẵng         ngoại tỉnh    Ngoại Tỉnh   
3                truong chinh,đà nẵng       truong chinh           NaN   
4                      cam le,đà nẵng                           Cẩm Lệ   
...                               ...                ...           ...   
4474                    a,thuan phuoc      a,thuan phuoc           NaN   
4475                 phuoc my,đà nẵng           phuoc my           NaN   
4476        nguyen gian thanh,đà nẵng  nguyen gian thanh           NaN   
4477             ngu hanh son,đà nẵng                     Ngũ Hành Sơn   
4478  thanh khe tay,thanh khe,đà nẵng                tay     Thanh Khê   

      Thành Phố  
0       Đà Nẵng  
1       Đà Nẵng  
2     Quảng Nam  
3       Đà Nẵng  
4       Đà Nẵng  
...         ...  
4474    Đà Nẵng  
4475    Đà Nẵng  
4476    Đà Nẵng  
4477    Đà Nẵng  
4478    Đà Nẵng  

[4479 rows x 4 columns]

In [201]:
district = customer['Quận'].unique()
print(district)

['Thanh Khê' nan 'Ngoại Tỉnh' 'Cẩm Lệ' 'Ngũ Hành Sơn' 'Liên Chiểu'
 'Hòa Vang' 'Sơn Trà' 'Hải Châu']


In [202]:
null_district = customer[customer['Quận'].isnull()]
null_district

customerid        DOB gender                    address  \
1          0000000034 1998-04-16    Nam           man thai,đà nẵng   
3          0000000081 1999-11-08    Nam       truong chinh,đà nẵng   
5          0000000109 1999-05-05    Nam          tam thuan,đà nẵng   
8          0000000229 1992-01-14    Nam      le đinh duong,đà nẵng   
9          0000000266 1995-01-01    Nam            le duan,đà nẵng   
...               ...        ...    ...                        ...   
4466        KH9704978 1997-05-18     Nữ     hoang van thai,đà nẵng   
4468        KH9743341 2000-02-25    Nam          nui thanh,đà nẵng   
4474        KH9855766 1995-07-05     Nữ              a,thuan phuoc   
4475        KH9958204 2001-01-01     Nữ           phuoc my,đà nẵng   
4476  WEBS00000043900 1988-06-17     Nữ  nguyen gian thanh,đà nẵng   

               Website           job        industry  Tuổi xem phim  \
1          KH0104|0333       student  health service             21   
3          KH0104|0293       student       economics             19   
5          KH0104|0191       student       education             20   
8          KH0104|2716  white collar       economics             27   
9          KH0104|0044   blue collar  social service             24   
...                ...           ...             ...            ...   
4466  Không có dữ liệu       student    construction             21   
4468  Không có dữ liệu      teenager           NoJob             19   
4474  Không có dữ liệu    specialist         finance             23   
4475  Không có dữ liệu      teenager           NoJob             18   
4476   KHWEBS|00006890    specialist    construction             30   

            Dữ liệu web              Đường Quận Thành Phố  
1     Have Data Website           man thai  NaN   Đà Nẵng  
3     Have Data Website       truong chinh  NaN   Đà Nẵng  
5     Have Data Website          tam thuan  NaN   Đà Nẵng  
8     Have Data Website      le đinh duong  NaN   Đà Nẵng  
9     Have Data Website            le duan  NaN   Đà Nẵng  
...                 ...                ...  ...       ...  
4466    No Data Website     hoang van thai  NaN   Đà Nẵng  
4468    No Data Website          nui thanh  NaN   Đà Nẵng  
4474    No Data Website      a,thuan phuoc  NaN   Đà Nẵng  
4475    No Data Website           phuoc my  NaN   Đà Nẵng  
4476  Have Data Website  nguyen gian thanh  NaN   Đà Nẵng  

[1181 rows x 12 columns]

In [203]:
city = customer['Thành Phố'].unique()
print(city)

['Đà Nẵng' 'Quảng Nam' 'Quảng Trị' 'Huế' 'Quảng Ngãi' 'Nghệ An' 'Gia Lai'
 'Quảng Bình' 'Hà Tĩnh' 'Hải Dương' 'Hà Nội' 'Khánh Hòa' 'Hồ Chí Minh'
 'Kon Tum' 'Đắk Lắk']


In [204]:
null_city = customer[customer['Thành Phố'].isnull()]
null_city

Empty DataFrame
Columns: [customerid, DOB, gender, address, Website, job, industry, Tuổi xem phim, Dữ liệu web, Đường, Quận, Thành Phố]
Index: []

### Thực hiện tiếp việc đọc các file dữ liệu từ đường , quân, thành phố Đà Nẵng để tối ưu hoa việc lọc cái giá trị null

In [205]:
tenduong=pd.read_excel('danh_sach_ten_cac_con_duong_tai_thanh_pho_da_nang_.xls')
tenduong.head()

Ten duong      Tenduong                         Từ khóa  \
0             3/2           3/2                3 tháng 2, Hải Châu   
1            30/4          30/4               30 tháng 4, Hải Châu   
2             2/9       2thang9  2 tháng 9, Hải Châu, quốc khánh,    
3  Phan Đinh Giót  PhanDinhGiot         Phan Đinh Giót, liên chiểu   
4     Lý Tế Xuyên     LyTeXuyen                        Lý Tế Xuyên   

                                               mo ta  \
0  TÊN ĐƯỜNG: 3 tháng 2\n* Vị trí con đường:\n1. ...   
1  TÊN ĐƯỜNG: 30 tháng 4\n* Vị trí con đường:\n1....   
2  TÊN ĐƯỜNG: 2 tháng 9\n* Vị trí con đường:\n1. ...   
3  TÊN ĐƯỜNG: Phan Đình Giót\n* Vị trí con đường:...   
4  TÊN ĐƯỜNG: Lý Tế Xuyên\n* Vị trí con đường:\n1...   

                                          Hình ảnh  Unnamed: 5  Unnamed: 6  \
0  https://congdulieu.vn/cdldnfiles/doanhnhantend...         NaN         NaN   
1  https://congdulieu.vn/cdldnfiles/doanhnhantend...         NaN         NaN   
2  https://congdulieu.vn/cdldnfiles/doanhnhantend...         NaN         NaN   
3  https://congdulieu.vn/cdldnfiles/doanhnhantend...         NaN         NaN   
4  https://congdulieu.vn/cdldnfiles/doanhnhantend...         NaN         NaN   

   Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  Quan  
0         NaN         NaN         NaN          NaN          NaN   NaN  
1         NaN         NaN         NaN          NaN          NaN   NaN  
2         NaN         NaN         NaN          NaN          NaN   NaN  
3         NaN         NaN         NaN          NaN          NaN   NaN  
4         NaN         NaN         NaN          NaN          NaN   NaN

In [206]:
tenduong = tenduong.loc[:, ~tenduong.columns.str.contains('^Unnamed')]
tenduong   

Ten duong      Tenduong                         Từ khóa  \
0                3/2           3/2                3 tháng 2, Hải Châu   
1               30/4          30/4               30 tháng 4, Hải Châu   
2                2/9       2thang9  2 tháng 9, Hải Châu, quốc khánh,    
3     Phan Đinh Giót  PhanDinhGiot         Phan Đinh Giót, liên chiểu   
4        Lý Tế Xuyên     LyTeXuyen                        Lý Tế Xuyên   
...              ...           ...                                ...   
1960       An Ngãi 5       AnNgai5                                NaN   
1961       An Ngãi 6       AnNgai6                                NaN   
1962       An Ngãi 7       AnNgai7                                NaN   
1963       An Ngãi 8       AnNgai8                                NaN   
1964       An Ngãi 9       AnNgai9                                NaN   

                                                  mo ta  \
0     TÊN ĐƯỜNG: 3 tháng 2\n* Vị trí con đường:\n1. ...   
1     TÊN ĐƯỜNG: 30 tháng 4\n* Vị trí con đường:\n1....   
2     TÊN ĐƯỜNG: 2 tháng 9\n* Vị trí con đường:\n1. ...   
3     TÊN ĐƯỜNG: Phan Đình Giót\n* Vị trí con đường:...   
4     TÊN ĐƯỜNG: Lý Tế Xuyên\n* Vị trí con đường:\n1...   
...                                                 ...   
1960  TÊN ĐƯỜNG: An Ngãi 5\n* Vị trí con đường: \n1....   
1961  TÊN ĐƯỜNG: An Ngãi 6\n* Vị trí con đường: \n1....   
1962  TÊN ĐƯỜNG: An Ngãi 7\n* Vị trí con đường: \n1....   
1963  TÊN ĐƯỜNG: An Ngãi 8\n* Vị trí con đường: \n1....   
1964  TÊN ĐƯỜNG: An Ngãi 9\n* Vị trí con đường: \n1....   

                                             Hình ảnh  Quan  
0     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
1     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
2     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
3     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
4     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
...                                                 ...   ...  
1960                                                NaN   NaN  
1961                                                NaN   NaN  
1962                                                NaN   NaN  
1963                                                NaN   NaN  
1964                                                NaN   NaN  

[1965 rows x 6 columns]

In [207]:
tenduong['mo ta'] = tenduong['mo ta'].astype(str)
tenduong['mo ta'] = tenduong['mo ta'].str.lower()

In [208]:
tenduong['Ten duong']=tenduong['Ten duong'].apply(remove_accents)
tenduong

Ten duong      Tenduong                         Từ khóa  \
0                3/2           3/2                3 tháng 2, Hải Châu   
1               30/4          30/4               30 tháng 4, Hải Châu   
2                2/9       2thang9  2 tháng 9, Hải Châu, quốc khánh,    
3     phan đinh giot  PhanDinhGiot         Phan Đinh Giót, liên chiểu   
4        ly te xuyen     LyTeXuyen                        Lý Tế Xuyên   
...              ...           ...                                ...   
1960       an ngai 5       AnNgai5                                NaN   
1961       an ngai 6       AnNgai6                                NaN   
1962       an ngai 7       AnNgai7                                NaN   
1963       an ngai 8       AnNgai8                                NaN   
1964       an ngai 9       AnNgai9                                NaN   

                                                  mo ta  \
0     tên đường: 3 tháng 2\n* vị trí con đường:\n1. ...   
1     tên đường: 30 tháng 4\n* vị trí con đường:\n1....   
2     tên đường: 2 tháng 9\n* vị trí con đường:\n1. ...   
3     tên đường: phan đình giót\n* vị trí con đường:...   
4     tên đường: lý tế xuyên\n* vị trí con đường:\n1...   
...                                                 ...   
1960  tên đường: an ngãi 5\n* vị trí con đường: \n1....   
1961  tên đường: an ngãi 6\n* vị trí con đường: \n1....   
1962  tên đường: an ngãi 7\n* vị trí con đường: \n1....   
1963  tên đường: an ngãi 8\n* vị trí con đường: \n1....   
1964  tên đường: an ngãi 9\n* vị trí con đường: \n1....   

                                             Hình ảnh  Quan  
0     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
1     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
2     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
3     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
4     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  
...                                                 ...   ...  
1960                                                NaN   NaN  
1961                                                NaN   NaN  
1962                                                NaN   NaN  
1963                                                NaN   NaN  
1964                                                NaN   NaN  

[1965 rows x 6 columns]

In [209]:
# check trong mo ta có bao gồm tên các quận tại đà nẵng không, nếu có thì add vào quận
specific_strings = ['hải châu', 'thanh khê', 'liên chiểu', 'ngũ hành sơn', 'sơn trà', 'cẩm lệ', 'hòa vang']
for string in specific_strings:
    tenduong.loc[tenduong['mo ta'].str.contains(string), 'quan'] = string
tenduong

Ten duong      Tenduong                         Từ khóa  \
0                3/2           3/2                3 tháng 2, Hải Châu   
1               30/4          30/4               30 tháng 4, Hải Châu   
2                2/9       2thang9  2 tháng 9, Hải Châu, quốc khánh,    
3     phan đinh giot  PhanDinhGiot         Phan Đinh Giót, liên chiểu   
4        ly te xuyen     LyTeXuyen                        Lý Tế Xuyên   
...              ...           ...                                ...   
1960       an ngai 5       AnNgai5                                NaN   
1961       an ngai 6       AnNgai6                                NaN   
1962       an ngai 7       AnNgai7                                NaN   
1963       an ngai 8       AnNgai8                                NaN   
1964       an ngai 9       AnNgai9                                NaN   

                                                  mo ta  \
0     tên đường: 3 tháng 2\n* vị trí con đường:\n1. ...   
1     tên đường: 30 tháng 4\n* vị trí con đường:\n1....   
2     tên đường: 2 tháng 9\n* vị trí con đường:\n1. ...   
3     tên đường: phan đình giót\n* vị trí con đường:...   
4     tên đường: lý tế xuyên\n* vị trí con đường:\n1...   
...                                                 ...   
1960  tên đường: an ngãi 5\n* vị trí con đường: \n1....   
1961  tên đường: an ngãi 6\n* vị trí con đường: \n1....   
1962  tên đường: an ngãi 7\n* vị trí con đường: \n1....   
1963  tên đường: an ngãi 8\n* vị trí con đường: \n1....   
1964  tên đường: an ngãi 9\n* vị trí con đường: \n1....   

                                             Hình ảnh  Quan        quan  
0     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN    hải châu  
1     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN    hải châu  
2     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN    hải châu  
3     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN  liên chiểu  
4     https://congdulieu.vn/cdldnfiles/doanhnhantend...   NaN      cẩm lệ  
...                                                 ...   ...         ...  
1960                                                NaN   NaN    hòa vang  
1961                                                NaN   NaN    hòa vang  
1962                                                NaN   NaN    hòa vang  
1963                                                NaN   NaN    hòa vang  
1964                                                NaN   NaN    hòa vang  

[1965 rows x 7 columns]

In [210]:
tracuu=tenduong[['Ten duong','quan']]
tracuu

Ten duong        quan
0                3/2    hải châu
1               30/4    hải châu
2                2/9    hải châu
3     phan đinh giot  liên chiểu
4        ly te xuyen      cẩm lệ
...              ...         ...
1960       an ngai 5    hòa vang
1961       an ngai 6    hòa vang
1962       an ngai 7    hòa vang
1963       an ngai 8    hòa vang
1964       an ngai 9    hòa vang

[1965 rows x 2 columns]

In [211]:
#add hoa khanh vao tracuu de tra cứu thành quận Liên Chiểu
new_record = {'Ten duong': 'hoa khanh', 'quan': 'liên chiểu'}
tracuu.loc[len(tracuu)] = new_record
tracuu

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_40928\2520740169.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracuu.loc[len(tracuu)] = new_record


Ten duong        quan
0                3/2    hải châu
1               30/4    hải châu
2                2/9    hải châu
3     phan đinh giot  liên chiểu
4        ly te xuyen      cẩm lệ
...              ...         ...
1961       an ngai 6    hòa vang
1962       an ngai 7    hòa vang
1963       an ngai 8    hòa vang
1964       an ngai 9    hòa vang
1965       hoa khanh  liên chiểu

[1966 rows x 2 columns]

In [212]:
quan_mapping2 = {
    "sơn trà": "Sơn Trà",
    "ngũ hành sơn": "Ngũ Hành Sơn", 
    "cẩm lệ": "Cẩm Lệ",
    "thanh khê": "Thanh Khê",
    "liên chiểu": "Liên Chiểu",
    "hòa vang": "Hòa Vang",
    "hải châu": "Hải Châu",
    "ngoại tỉnh":"Ngoại Tỉnh"
}

tracuu["quan"] = tracuu["quan"].map(quan_mapping2)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_40928\161112046.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tracuu["quan"] = tracuu["quan"].map(quan_mapping2)


In [213]:
n= tracuu.duplicated(subset=['Ten duong']).sum()
n

158

In [214]:
tracuu = tracuu.drop_duplicates(subset=['Ten duong'])

In [215]:
customer_full = pd.merge(customer, tracuu, how='left', left_on='Đường', right_on='Ten duong')
customer_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4479 entries, 0 to 4478
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   customerid     4479 non-null   object        
 1   DOB            4476 non-null   datetime64[ns]
 2   gender         4479 non-null   object        
 3   address        4479 non-null   object        
 4   Website        4479 non-null   object        
 5   job            4479 non-null   object        
 6   industry       4479 non-null   object        
 7   Tuổi xem phim  4476 non-null   Int64         
 8   Dữ liệu web    4479 non-null   object        
 9   Đường          4479 non-null   object        
 10  Quận           3298 non-null   object        
 11  Thành Phố      4479 non-null   object        
 12  Ten duong      976 non-null    object        
 13  quan           873 non-null    object        
dtypes: Int64(1), datetime64[ns](1), object(12)
memory usage: 494.4+ KB


In [216]:
customer_full = pd.merge(customer, tracuu, how='left', left_on='Đường', right_on='Ten duong')
customer_full['Quận'] = customer_full['quan'].combine_first(customer_full['Quận'])
customer_full.drop(['Ten duong', 'quan'], axis=1, inplace=True)
customer_full

customerid        DOB gender                          address  \
0          0000000014 1999-04-18     Nữ   hoa khe quan thanh khe,đà nẵng   
1          0000000034 1998-04-16    Nam                 man thai,đà nẵng   
2          0000000051 1993-12-16    Nam        que son quang nam,đà nẵng   
3          0000000081 1999-11-08    Nam             truong chinh,đà nẵng   
4          0000000098 1994-10-01    Nam                   cam le,đà nẵng   
...               ...        ...    ...                              ...   
4474        KH9855766 1995-07-05     Nữ                    a,thuan phuoc   
4475        KH9958204 2001-01-01     Nữ                 phuoc my,đà nẵng   
4476  WEBS00000043900 1988-06-17     Nữ        nguyen gian thanh,đà nẵng   
4477  WEBS00000044909 1996-09-08     Nữ             ngu hanh son,đà nẵng   
4478  WEBS00000046015 2002-04-26     Nữ  thanh khe tay,thanh khe,đà nẵng   

               Website          job        industry  Tuổi xem phim  \
0          KH0104|0345      student        computer             20   
1          KH0104|0333      student  health service             21   
2          KH0104|0255  blue collar       economics             25   
3          KH0104|0293      student       economics             19   
4         KH0104|40580  blue collar  health service             24   
...                ...          ...             ...            ...   
4474  Không có dữ liệu   specialist         finance             23   
4475  Không có dữ liệu     teenager           NoJob             18   
4476   KHWEBS|00006890   specialist    construction             30   
4477   KHWEBS|00007899  blue collar         finance             22   
4478   KHWEBS|00009005     teenager           NoJob             17   

            Dữ liệu web              Đường          Quận  Thành Phố  
0     Have Data Website            hoa khe     Thanh Khê    Đà Nẵng  
1     Have Data Website           man thai           NaN    Đà Nẵng  
2     Have Data Website         ngoại tỉnh    Ngoại Tỉnh  Quảng Nam  
3     Have Data Website       truong chinh           NaN    Đà Nẵng  
4     Have Data Website                           Cẩm Lệ    Đà Nẵng  
...                 ...                ...           ...        ...  
4474    No Data Website      a,thuan phuoc           NaN    Đà Nẵng  
4475    No Data Website           phuoc my       Sơn Trà    Đà Nẵng  
4476  Have Data Website  nguyen gian thanh     Thanh Khê    Đà Nẵng  
4477  Have Data Website                     Ngũ Hành Sơn    Đà Nẵng  
4478  Have Data Website                tay     Thanh Khê    Đà Nẵng  

[4479 rows x 12 columns]

In [217]:
customer_full['Quận'] = customer_full['Quận'].fillna('Không xác định')

In [218]:
null_records = customer_full.loc[(customer_full['Thành Phố'] == 'Đà Nẵng') & 
                               (customer_full['Quận'] == '')]
null_records

Empty DataFrame
Columns: [customerid, DOB, gender, address, Website, job, industry, Tuổi xem phim, Dữ liệu web, Đường, Quận, Thành Phố]
Index: []

In [219]:
print(customer_full['Quận'].isnull().any())

False


In [220]:
district_col = customer_full['Quận']
district_col

0            Thanh Khê
1       Không xác định
2           Ngoại Tỉnh
3       Không xác định
4               Cẩm Lệ
             ...      
4474    Không xác định
4475           Sơn Trà
4476         Thanh Khê
4477      Ngũ Hành Sơn
4478         Thanh Khê
Name: Quận, Length: 4479, dtype: object

In [221]:
customer_full.isnull().any()

customerid       False
DOB               True
gender           False
address          False
Website          False
job              False
industry         False
Tuổi xem phim     True
Dữ liệu web      False
Đường            False
Quận             False
Thành Phố        False
dtype: bool

## Xử lý các dữ liệu bị lỗi của DOB

In [222]:
customer_DOB_full = customer_full[customer_full['DOB'].isnull()]
customer_DOB_full

customerid DOB gender                                      address  \
1177  0001013549 NaT    Nam                         ngu hanh son,đà nẵng   
1563  0001077023 NaT    Nam  banh thai buoi hoa khanh lien chieu,đà nẵng   
2207  0001120656 NaT    Nam                    quan ngu hanh son,đà nẵng   

           Website       job industry  Tuổi xem phim        Dữ liệu web  \
1177  KH0104|24922  teenager    NoJob           <NA>  Have Data Website   
1563  KH0104|27958  teenager    NoJob           <NA>  Have Data Website   
2207  KH0104|46001  teenager    NoJob           <NA>  Have Data Website   

                         Đường          Quận Thành Phố  
1177                            Ngũ Hành Sơn   Đà Nẵng  
1563  banh thai buoi hoa khanh    Liên Chiểu   Đà Nẵng  
2207                            Ngũ Hành Sơn   Đà Nẵng

Nhận ra là 3 trường hợp bị lỗi là sau khi chuẩn hóa này là đều thuộc loại khách hàng là teenager, vậy nên thực hiện việc gán nhãn vào độ tuổi này là 13 tuổi 

In [223]:
customer_full.loc[customer_full['DOB'].isnull(), 'DOB'] = 13

In [224]:
customer_full['Tuổi xem phim'] = customer_full['Tuổi xem phim'].fillna(13)

In [225]:
customer_full.isnull().any()

customerid       False
DOB              False
gender           False
address          False
Website          False
job              False
industry         False
Tuổi xem phim    False
Dữ liệu web      False
Đường            False
Quận             False
Thành Phố        False
dtype: bool

# Đã hoàn thành việc xử lý với file customer và đưa ra được một số vấn đề sau : 
    -- Đã xử lý một số kí tự đặc biệt của customerid
    -- Đã chuyển được cột DOB về giá trị cần sử dụng sau khi đã bị mã hóa
    -- Đã hoàn thành việc xử lý missing value cột Website
    -- Đã hoàn thành việc tạo ra cột Dữ liệu web dựa vào giá trị cột Website
    -- Đã hoàn thành việc xử lý missing value cột industry tại giá trị teenager của cột job
    -- Đã tạo ra được cột "Tuổi xem phim" của khách hàng
    -- Đã tách được dữ liệu cột address thành các cột "Đường","Quận","Thành phố"

## Xuất ra file excel

In [226]:
# drop cột đường
customer_full=customer_full.drop(['Đường'], axis=1)

In [227]:
customer_full.to_excel("Customers.xlsx")

# Làm việc với bảng ticket

## Đọc dữ liệu

In [228]:
tickets = pd.read_excel(excel_file, sheet_name='ticket')

In [229]:
tickets.head()

orderid cashier            saledate    total  customerid  \
0  10006052019B0225  emp002 2019-05-06 16:40:43  90000.0  0000000014   
1  10006052019B0225  emp002 2019-05-06 16:40:43  90000.0  0000000014   
2  10022052019B0167  emp011 2019-05-22 20:30:28  90000.0  0000000034   
3  10022052019B0167  emp011 2019-05-22 20:30:28  90000.0  0000000034   
4  10130052019B0141  emp005 2019-05-30 19:28:44  90000.0  0000000034   

   ticketcode       date      time slot  room  \
0    20074925 2019-05-06  18:15:00  G04     3   
1    20074924 2019-05-06  18:15:00  G03     3   
2    20097042 2019-05-22  20:45:00  E04     2   
3    20097041 2019-05-22  20:45:00  E03     2   
4    20106761 2019-05-30  19:30:00  F04     1   

                                      film slot type ticket type  \
0                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
1                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
3  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
4                   NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN  Thành viên   

   ticket price popcorn  
0         45000   Không  
1         45000   Không  
2         45000   Không  
3         45000   Không  
4         45000   Không

In [230]:
tickets.tail()

orderid cashier            saledate     total  \
35469  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35470  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35471  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35472  12508052019B0036  emp007 2019-05-08 19:26:47   90000.0   
35473  12508052019B0036  emp007 2019-05-08 19:26:47   90000.0   

            customerid  ticketcode       date      time slot  room  \
35469  WEBS00000044909    20107072 2019-05-30  21:35:00  B10     4   
35470  WEBS00000044909    20107071 2019-05-30  21:35:00  B09     4   
35471  WEBS00000044909    20107069 2019-05-30  21:35:00  B07     4   
35472  WEBS00000046015    20077797 2019-05-08  19:15:00  C14     4   
35473  WEBS00000046015    20077796 2019-05-08  19:15:00  C13     4   

                                          film slot type ticket type  \
35469  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35470  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35471  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35472                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
35473                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   

       ticket price popcorn  
35469         45000   Không  
35470         45000   Không  
35471         45000   Không  
35472         45000   Không  
35473         45000   Không

In [231]:
tickets.shape

(35474, 15)

In [232]:
tickets.columns

Index(['orderid', 'cashier', 'saledate', 'total', 'customerid', 'ticketcode',
       'date', 'time', 'slot', 'room', 'film', 'slot type', 'ticket type',
       'ticket price', 'popcorn'],
      dtype='object')

In [233]:
tickets.isnull().any()

orderid          True
cashier         False
saledate         True
total            True
customerid      False
ticketcode      False
date            False
time            False
slot            False
room            False
film            False
slot type       False
ticket type     False
ticket price    False
popcorn          True
dtype: bool

## Làm việc với cột orderid

In [234]:
print(tickets["orderid"].dtype)

object


In [235]:
tickets["orderid"].isnull().values.any()
# Có null ở chỗ orderid

True

In [236]:
orderid_count = tickets['orderid'].value_counts()
print(orderid_count)

orderid
10026052019B0285    43
12511052019B0007    32
10015052019B0081    27
12521052019B0026    27
10017052019B0148    23
                    ..
10106052019B0121     1
10025052019B0287     1
10012052019B0213     1
10012052019B0335     1
10014052019B0114     1
Name: count, Length: 14598, dtype: int64


Kết quả ở trên của các orderid bị trùng nhiều và số lượng trùng

In [237]:
# Lấy các giá trị trùng lặp của cột orderid 
orderid_duplicate = tickets['orderid'].duplicated(keep=False)
tickets.loc[orderid_duplicate].shape

(33039, 15)

=>> Bị trùng 33039 records

In [238]:
tickets_orderid_null = tickets[tickets['orderid'].isnull()]
tickets_orderid_null.head()

orderid  cashier saledate  total  customerid  ticketcode       date  \
23      NaN  Website      NaT    NaN  0000000228    20100926 2019-05-25   
24      NaN  Website      NaT    NaN  0000000228    20100927 2019-05-25   
580     NaN  Website      NaT    NaN  0000011318    20092413 2019-05-18   
581     NaN  Website      NaT    NaN  0000011318    20092412 2019-05-18   
582     NaN  Website      NaT    NaN  0000011318    20092411 2019-05-18   

         time slot  room                            film slot type  \
23   19:45:00  G09     3                ALADDIN (PD) (G)       ĐƠN   
24   19:45:00  G10     3                ALADDIN (PD) (G)       ĐƠN   
580  18:40:00  G09     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
581  18:40:00  G08     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
582  18:40:00  G07     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   

    ticket type  ticket price popcorn  
23   Thành viên         45000     NaN  
24   Thành viên         45000     NaN  
580  Thành viên         45000     NaN  
581  Thành viên         45000     NaN  
582  Thành viên         45000     NaN

In [239]:
tickets_orderid_null.shape

(96, 15)

=>> Nhận ra là nếu orderid null thì saledate và total null, ngoài ra thì cashier là website thì orderid nó sẽ null =>> nên làm việc với cột cashier

### Đặt lại các orderid lần lượt là Web01,  Web02 ,... cho các orderid null

In [240]:
# Lấy chỉ số cho các bản ghi mà 'orderid' là null và sắp xếp theo 'customerid' và 'date'
null_orderid_records = tickets[tickets['orderid'].isnull()].sort_values(by=['customerid', 'date'])

# Tạo một biến để theo dõi orderid hiện tại và nhóm hiện tại
current_orderid = 0
current_group = None

# Tạo orderid mới cho mỗi bản ghi có orderid null
for index, row in null_orderid_records.iterrows():
    # Kiểm tra xem nhóm hiện tại có khác với nhóm trước đó không (dựa trên customerid và date)
    group = (row['customerid'], row['date'])
    if group != current_group:
        current_group = group
        current_orderid += 1  # Chỉ tăng orderid nếu chúng ta có một nhóm mới

    # Định dạng orderid mới và cập nhật trong DataFrame gốc
    new_orderid = 'WEB' + str(current_orderid).zfill(2)
    tickets.at[index, 'orderid'] = new_orderid

# Loại bỏ cột group_id nếu nó tồn tại
if 'group_id' in tickets.columns:
    tickets.drop('group_id', axis=1, inplace=True)




In [241]:
tickets["orderid"].isnull().values.any()

False

In [242]:
tickets[tickets["cashier"] == "Website"]

orderid  cashier saledate  total  customerid  ticketcode       date  \
23      WEB01  Website      NaT    NaN  0000000228    20100926 2019-05-25   
24      WEB01  Website      NaT    NaN  0000000228    20100927 2019-05-25   
580     WEB02  Website      NaT    NaN  0000011318    20092413 2019-05-18   
581     WEB02  Website      NaT    NaN  0000011318    20092412 2019-05-18   
582     WEB02  Website      NaT    NaN  0000011318    20092411 2019-05-18   
...       ...      ...      ...    ...         ...         ...        ...   
23102   WEB43  Website      NaT    NaN  0003008617    20106999 2019-05-30   
23103   WEB43  Website      NaT    NaN  0003008617    20106998 2019-05-30   
23106   WEB42  Website      NaT    NaN  0003008617    20091106 2019-05-17   
23107   WEB42  Website      NaT    NaN  0003008617    20091105 2019-05-17   
23108   WEB42  Website      NaT    NaN  0003008617    20091107 2019-05-17   

           time slot  room                                     film slot type  \
23     19:45:00  G09     3                         ALADDIN (PD) (G)       ĐƠN   
24     19:45:00  G10     3                         ALADDIN (PD) (G)       ĐƠN   
580    18:40:00  G09     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
581    18:40:00  G08     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
582    18:40:00  G07     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
...         ...  ...   ...                                      ...       ...   
23102  21:35:00  H09     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23103  21:35:00  H08     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23106  20:15:00  F14     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23107  20:15:00  F13     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23108  20:15:00  F15     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   

      ticket type  ticket price popcorn  
23     Thành viên         45000     NaN  
24     Thành viên         45000     NaN  
580    Thành viên         45000     NaN  
581    Thành viên         45000     NaN  
582    Thành viên         45000     NaN  
...           ...           ...     ...  
23102  Thành viên         45000     NaN  
23103  Thành viên         45000     NaN  
23106  Thành viên         45000     NaN  
23107  Thành viên         45000     NaN  
23108  Thành viên         45000     NaN  

[96 rows x 15 columns]

## Làm việc với cột cashier

In [243]:
print(tickets["cashier"].dtype)

object


In [244]:
tickets["cashier"].isnull().values.any()

False

=>> Không có null tại cashier

In [245]:
cashier = tickets['cashier'].unique()
print(cashier)

['emp002' 'emp011' 'emp005' 'emp007' 'emp006' 'Website' 'emp004' 'emp001'
 'emp009' 'emp012' 'emp008' 'emp010' 'emp014' 'emp003' 'emp015' 'emp013']


=>> Có 1 trường hợp là cashier là Website =>> đây có thể là trường hợp đặt online , đồng thời tổng cộng có 15 máy tính tiền( người bán)

### Check xem đã xử lý được trường hợp orderid null trong trường hợp cashier là website chưa 

In [246]:
tickets[tickets["cashier"] == "Website"].tail()

orderid  cashier saledate  total  customerid  ticketcode       date  \
23102   WEB43  Website      NaT    NaN  0003008617    20106999 2019-05-30   
23103   WEB43  Website      NaT    NaN  0003008617    20106998 2019-05-30   
23106   WEB42  Website      NaT    NaN  0003008617    20091106 2019-05-17   
23107   WEB42  Website      NaT    NaN  0003008617    20091105 2019-05-17   
23108   WEB42  Website      NaT    NaN  0003008617    20091107 2019-05-17   

           time slot  room                                     film slot type  \
23102  21:35:00  H09     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23103  21:35:00  H08     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23106  20:15:00  F14     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23107  20:15:00  F13     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23108  20:15:00  F15     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   

      ticket type  ticket price popcorn  
23102  Thành viên         45000     NaN  
23103  Thành viên         45000     NaN  
23106  Thành viên         45000     NaN  
23107  Thành viên         45000     NaN  
23108  Thành viên         45000     NaN

In [247]:
tickets[tickets["cashier"] == "Website"].head()

orderid  cashier saledate  total  customerid  ticketcode       date  \
23    WEB01  Website      NaT    NaN  0000000228    20100926 2019-05-25   
24    WEB01  Website      NaT    NaN  0000000228    20100927 2019-05-25   
580   WEB02  Website      NaT    NaN  0000011318    20092413 2019-05-18   
581   WEB02  Website      NaT    NaN  0000011318    20092412 2019-05-18   
582   WEB02  Website      NaT    NaN  0000011318    20092411 2019-05-18   

         time slot  room                            film slot type  \
23   19:45:00  G09     3                ALADDIN (PD) (G)       ĐƠN   
24   19:45:00  G10     3                ALADDIN (PD) (G)       ĐƠN   
580  18:40:00  G09     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
581  18:40:00  G08     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
582  18:40:00  G07     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   

    ticket type  ticket price popcorn  
23   Thành viên         45000     NaN  
24   Thành viên         45000     NaN  
580  Thành viên         45000     NaN  
581  Thành viên         45000     NaN  
582  Thành viên         45000     NaN

In [248]:
tickets[(tickets["cashier"] == "Website")]["orderid"].isnull().any()

False

=>> Không còn giá trị null tại orderid nếu cashier là website , chỉ còn tại popcorn , saledate và total

## Làm việc với customerid

In [249]:
print(tickets["customerid"].dtype)

object


In [250]:
tickets["customerid"].isnull().values.any()

False

=>> Không có giá trị null tại cột customerid

In [251]:
tickets['customerid'] = tickets['customerid'].apply(clean_custid)

In [252]:
customerid= tickets['customerid'].unique()
customerid

array(['0000000014', '0000000034', '0000000051', ..., 'WEBS00000043900',
       'WEBS00000044909', 'WEBS00000046015'], dtype=object)

=>> Customerid không theo quy tắc chung

In [253]:
customerid_count = tickets['customerid'].value_counts()
print(customerid_count)

customerid
KH6166700     10132
0000029127     7105
0001121703      507
KH3742976        54
0003004563       52
              ...  
0001023931        1
0001023923        1
0001165762        1
0001168337        1
0000027879        1
Name: count, Length: 4479, dtype: int64


=>> Có một số khách hàng chiếm rất nhiều lượt mua ( mua nhiều ) trên tổng số lượt mua của rạp , điển hình là khách hàng có mã KH6166700 với 10132 , chiếm gần 1/3, đồng thời khách hàng có customerid là 7105 cũng chiếm rất nhiều ,tuy nhiên lại có một số khách hàng có rất ít , chỉ có 1 lần mua vé. Nên là có thể phân tích một số khách hàng mua vé nhiều ( tại sao mua vé nhiều, lý do mua vé , mua nhiều vậy có khi nò là tổ chức hoặc fan bao rạp hoặc có thể là mấy người đặt hộ ?)

In [254]:
tickets[tickets['customerid'] == 'KH6166700'].groupby('film')['customerid'].count()

film
(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU KÝ (G)     230
(PĐ) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU KÝ (G)      14
ALADDIN (LT) (G)                                        311
ALADDIN (PD) (G)                                        217
AVENGERS: HỒI KẾT                                      2026
CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)                 287
CÀ CHỚN ANH ĐỪNG ĐI                                      59
JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)                 883
LẬT MẶT: NHÀ CÓ KHÁCH                                   152
MẸ MA THAN KHÓC LA LLORONA (C18)                       3305
NGÔI ĐỀN KỲ QUÁI (C18)                                  813
NỤ HÔN MA QUÁI (C18)                                     47
POKÉMON: THÁM TỬ PIKACHU (C13)                          922
QUÝ CÔ LỪA ĐẢO                                           55
THẰNG EM LÝ TƯỞNG                                       205
VÔ GIAN ĐẠO (C18)                                       134
VỢ BA                              

=>> Đặt nhiều nhất tại 2 phim Me Ma than khóc La LLORONA và Avenger

### Tách ra 2 dataframe nhỏ là customerid có webs và không có web

In [255]:
tickets_without_webs = tickets[tickets['customerid'].apply(lambda x: not x.startswith('WEBS'))]
tickets_with_webs = tickets[tickets['customerid'].apply(lambda x: x.startswith('WEBS'))]

In [256]:
tickets_without_webs.head()

orderid cashier            saledate    total  customerid  \
0  10006052019B0225  emp002 2019-05-06 16:40:43  90000.0  0000000014   
1  10006052019B0225  emp002 2019-05-06 16:40:43  90000.0  0000000014   
2  10022052019B0167  emp011 2019-05-22 20:30:28  90000.0  0000000034   
3  10022052019B0167  emp011 2019-05-22 20:30:28  90000.0  0000000034   
4  10130052019B0141  emp005 2019-05-30 19:28:44  90000.0  0000000034   

   ticketcode       date      time slot  room  \
0    20074925 2019-05-06  18:15:00  G04     3   
1    20074924 2019-05-06  18:15:00  G03     3   
2    20097042 2019-05-22  20:45:00  E04     2   
3    20097041 2019-05-22  20:45:00  E03     2   
4    20106761 2019-05-30  19:30:00  F04     1   

                                      film slot type ticket type  \
0                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
1                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
3  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
4                   NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN  Thành viên   

   ticket price popcorn  
0         45000   Không  
1         45000   Không  
2         45000   Không  
3         45000   Không  
4         45000   Không

In [257]:
tickets_without_webs.shape

(35465, 15)

In [258]:
tickets_with_webs

orderid cashier            saledate     total  \
35465  10009052019B0331  emp008 2019-05-09 21:00:51   90000.0   
35466  10009052019B0332  emp008 2019-05-09 21:13:47   90000.0   
35467  10009052019B0332  emp008 2019-05-09 21:13:47   90000.0   
35468  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35469  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35470  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35471  10130052019B0192  emp005 2019-05-30 21:49:46  180000.0   
35472  12508052019B0036  emp007 2019-05-08 19:26:47   90000.0   
35473  12508052019B0036  emp007 2019-05-08 19:26:47   90000.0   

            customerid  ticketcode       date      time slot  room  \
35465  WEBS00000043900    20079496 2019-05-09  22:25:00  H03     2   
35466  WEBS00000043900    20079501 2019-05-09  21:30:00  F10     3   
35467  WEBS00000043900    20079502 2019-05-09  21:30:00  F11     3   
35468  WEBS00000044909    20107070 2019-05-30  21:35:00  B08     4   
35469  WEBS00000044909    20107072 2019-05-30  21:35:00  B10     4   
35470  WEBS00000044909    20107071 2019-05-30  21:35:00  B09     4   
35471  WEBS00000044909    20107069 2019-05-30  21:35:00  B07     4   
35472  WEBS00000046015    20077797 2019-05-08  19:15:00  C14     4   
35473  WEBS00000046015    20077796 2019-05-08  19:15:00  C13     4   

                                          film slot type ticket type  \
35465         MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI  Thành viên   
35466                          ƯỚC HẸN MÙA THU       ĐƠN  Thành viên   
35467                          ƯỚC HẸN MÙA THU       ĐƠN  Thành viên   
35468  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35469  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35470  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35471  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35472                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
35473                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   

       ticket price popcorn  
35465         90000   Không  
35466         45000   Không  
35467         45000   Không  
35468         45000   Không  
35469         45000   Không  
35470         45000   Không  
35471         45000   Không  
35472         45000   Không  
35473         45000   Không

In [259]:
tickets_with_webs.shape

(9, 15)

=>> Có sự chênh lệch quá rõ ràng giữa customerid có webs là không webs ? Nhận xét xem thử là nếu customerid có web thì có phải là chỉ ở emp005 , 007 và 008 không ? Tức là có phải chỉ 3 thằng ni chuyên sài cho customerid có webs ko ?

#### Kiểm tra thử idea trên có đúng không ? 

In [260]:
# Kiểm tra trong tickets_with_webs
with_webs_cashiers = set(tickets_with_webs['cashier'].unique())
expected_cashiers = {'emp005', 'emp007', 'emp008'}
is_match_with_webs = expected_cashiers.issubset(with_webs_cashiers)

# Kiểm tra trong tickets_without_webs
without_webs_cashiers = set(tickets_without_webs['cashier'].unique())
is_match_without_webs = expected_cashiers.issubset(without_webs_cashiers)

print("Cashiers in tickets_with_webs:", is_match_with_webs)
print("Cashiers in tickets_without_webs:", is_match_without_webs)


Cashiers in tickets_with_webs: True
Cashiers in tickets_without_webs: True


==>> Idea trên bị sai =>> loại bỏ ý tưởng


## Làm việc với cột popcorn 

In [261]:
print(tickets["popcorn"].dtype)

object


In [262]:
tickets["popcorn"].isnull().values.any()

True

In [263]:
tickets['popcorn'].fillna('Website/Liên hệ tại quầy', inplace=True)

In [264]:
popcorn_vals = tickets['popcorn'].value_counts()
popcorn_vals

popcorn
Không                       35287
Website/Liên hệ tại quầy       96
Có                             91
Name: count, dtype: int64

=>> Đa phần không mua Popcorn

## Làm việc với cột saledate

### Tách cột saledate ra thành cột Saletime và Saledate (saledate chỉ để lại dạng dữ liệu year-month-date)

In [265]:
print(tickets["saledate"].dtype)

datetime64[ns]


In [266]:
tickets["saledate"].isnull().values.any()

True

=>> Có null ở saledate

In [267]:
# Tách thành cột time
tickets["saletime"] = tickets["saledate"].dt.time

# Tách thành cột date với định dạng year-month-date    
tickets["saledate"] = tickets["saledate"].dt.strftime("%Y-%m-%d")

In [268]:
tickets.head()

orderid cashier    saledate    total  customerid  ticketcode  \
0  10006052019B0225  emp002  2019-05-06  90000.0  0000000014    20074925   
1  10006052019B0225  emp002  2019-05-06  90000.0  0000000014    20074924   
2  10022052019B0167  emp011  2019-05-22  90000.0  0000000034    20097042   
3  10022052019B0167  emp011  2019-05-22  90000.0  0000000034    20097041   
4  10130052019B0141  emp005  2019-05-30  90000.0  0000000034    20106761   

        date      time slot  room                                     film  \
0 2019-05-06  18:15:00  G04     3                        AVENGERS: HỒI KẾT   
1 2019-05-06  18:15:00  G03     3                        AVENGERS: HỒI KẾT   
2 2019-05-22  20:45:00  E04     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)   
3 2019-05-22  20:45:00  E03     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)   
4 2019-05-30  19:30:00  F04     1                   NGÔI ĐỀN KỲ QUÁI (C18)   

  slot type ticket type  ticket price popcorn  saletime  
0       ĐƠN  Thành viên         45000   Không  16:40:43  
1       ĐƠN  Thành viên         45000   Không  16:40:43  
2       ĐƠN  Thành viên         45000   Không  20:30:28  
3       ĐƠN  Thành viên         45000   Không  20:30:28  
4       ĐƠN  Thành viên         45000   Không  19:28:44

In [269]:
saledate_null = tickets['saledate'].isnull().sum() 

print(saledate_null)

96


=>> Những cột saledate null thì vẫn như làm việc ở trên , nếu cashier là website thì saledate null =>> nhận ra là saledate bằng date =>> gán những giá trị null của saledate bằng giá trị của date

### Gán giá trị 

In [270]:

tickets[tickets['saledate'].isnull()]

orderid  cashier saledate  total  customerid  ticketcode       date  \
23      WEB01  Website      NaN    NaN  0000000228    20100926 2019-05-25   
24      WEB01  Website      NaN    NaN  0000000228    20100927 2019-05-25   
580     WEB02  Website      NaN    NaN  0000011318    20092413 2019-05-18   
581     WEB02  Website      NaN    NaN  0000011318    20092412 2019-05-18   
582     WEB02  Website      NaN    NaN  0000011318    20092411 2019-05-18   
...       ...      ...      ...    ...         ...         ...        ...   
23102   WEB43  Website      NaN    NaN  0003008617    20106999 2019-05-30   
23103   WEB43  Website      NaN    NaN  0003008617    20106998 2019-05-30   
23106   WEB42  Website      NaN    NaN  0003008617    20091106 2019-05-17   
23107   WEB42  Website      NaN    NaN  0003008617    20091105 2019-05-17   
23108   WEB42  Website      NaN    NaN  0003008617    20091107 2019-05-17   

           time slot  room                                     film slot type  \
23     19:45:00  G09     3                         ALADDIN (PD) (G)       ĐƠN   
24     19:45:00  G10     3                         ALADDIN (PD) (G)       ĐƠN   
580    18:40:00  G09     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
581    18:40:00  G08     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
582    18:40:00  G07     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
...         ...  ...   ...                                      ...       ...   
23102  21:35:00  H09     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23103  21:35:00  H08     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23106  20:15:00  F14     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23107  20:15:00  F13     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23108  20:15:00  F15     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   

      ticket type  ticket price                   popcorn saletime  
23     Thành viên         45000  Website/Liên hệ tại quầy      NaN  
24     Thành viên         45000  Website/Liên hệ tại quầy      NaN  
580    Thành viên         45000  Website/Liên hệ tại quầy      NaN  
581    Thành viên         45000  Website/Liên hệ tại quầy      NaN  
582    Thành viên         45000  Website/Liên hệ tại quầy      NaN  
...           ...           ...                       ...      ...  
23102  Thành viên         45000  Website/Liên hệ tại quầy      NaN  
23103  Thành viên         45000  Website/Liên hệ tại quầy      NaN  
23106  Thành viên         45000  Website/Liên hệ tại quầy      NaN  
23107  Thành viên         45000  Website/Liên hệ tại quầy      NaN  
23108  Thành viên         45000  Website/Liên hệ tại quầy      NaN  

[96 rows x 16 columns]

In [271]:
# Chuyển đổi cột 'date' thành kiểu Timestamp
tickets['date'] = pd.to_datetime(tickets['date'])

# Thay thế các giá trị NaN trong 'saledate' bằng các giá trị từ cột 'date'
tickets['saledate'].fillna(tickets['date'], inplace=True)

In [272]:
# Lọc DataFrame để chỉ lấy những bản ghi có 'cashier' là 'Website'
website_records = tickets[tickets['cashier'] == 'Website']

# Cập nhật cột 'saledate' để chỉ giữ lại phần ngày
tickets.loc[website_records.index, 'saledate'] = tickets.loc[website_records.index, 'saledate'].apply(lambda x: x.normalize().date())




In [273]:
tickets[tickets["cashier"] == "Website"].head()

orderid  cashier    saledate  total  customerid  ticketcode       date  \
23    WEB01  Website  2019-05-25    NaN  0000000228    20100926 2019-05-25   
24    WEB01  Website  2019-05-25    NaN  0000000228    20100927 2019-05-25   
580   WEB02  Website  2019-05-18    NaN  0000011318    20092413 2019-05-18   
581   WEB02  Website  2019-05-18    NaN  0000011318    20092412 2019-05-18   
582   WEB02  Website  2019-05-18    NaN  0000011318    20092411 2019-05-18   

         time slot  room                            film slot type  \
23   19:45:00  G09     3                ALADDIN (PD) (G)       ĐƠN   
24   19:45:00  G10     3                ALADDIN (PD) (G)       ĐƠN   
580  18:40:00  G09     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
581  18:40:00  G08     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
582  18:40:00  G07     1  POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   

    ticket type  ticket price                   popcorn saletime  
23   Thành viên         45000  Website/Liên hệ tại quầy      NaT  
24   Thành viên         45000  Website/Liên hệ tại quầy      NaT  
580  Thành viên         45000  Website/Liên hệ tại quầy      NaT  
581  Thành viên         45000  Website/Liên hệ tại quầy      NaT  
582  Thành viên         45000  Website/Liên hệ tại quầy      NaT

In [274]:
tickets[tickets["cashier"] == "Website"].tail()

orderid  cashier    saledate  total  customerid  ticketcode       date  \
23102   WEB43  Website  2019-05-30    NaN  0003008617    20106999 2019-05-30   
23103   WEB43  Website  2019-05-30    NaN  0003008617    20106998 2019-05-30   
23106   WEB42  Website  2019-05-17    NaN  0003008617    20091106 2019-05-17   
23107   WEB42  Website  2019-05-17    NaN  0003008617    20091105 2019-05-17   
23108   WEB42  Website  2019-05-17    NaN  0003008617    20091107 2019-05-17   

           time slot  room                                     film slot type  \
23102  21:35:00  H09     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23103  21:35:00  H08     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23106  20:15:00  F14     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23107  20:15:00  F13     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23108  20:15:00  F15     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   

      ticket type  ticket price                   popcorn saletime  
23102  Thành viên         45000  Website/Liên hệ tại quầy      NaT  
23103  Thành viên         45000  Website/Liên hệ tại quầy      NaT  
23106  Thành viên         45000  Website/Liên hệ tại quầy      NaT  
23107  Thành viên         45000  Website/Liên hệ tại quầy      NaT  
23108  Thành viên         45000  Website/Liên hệ tại quầy      NaT

In [275]:
tickets["saledate"].isnull().values.any()

False

=>> Không còn null

## Làm việc với cột ticket price

In [276]:
tickets["ticket price"].isnull().values.any()


False

=>> không có null

In [277]:
ticket_price= tickets['ticket price'].unique()
ticket_price

array([ 45000,  90000,  75000, 160000,      0], dtype=int64)

=>> Có 5 mức giá là 45000, 90000,75000 và 160000 và cuối cùng là giá vé bằng 0 (nên kiểm tra giá vé tại sao bằng 0)

### Kiểm tra 5 mức vé có đặc điểm gì 

#### Với giá vé là 45000

In [278]:
selection_tickets = tickets[tickets['ticket price'] == 45000][['slot', 'room','time','film','slot type','saledate']]
selection_tickets

slot  room      time                                     film slot type  \
0      G04     3  18:15:00                        AVENGERS: HỒI KẾT       ĐƠN   
1      G03     3  18:15:00                        AVENGERS: HỒI KẾT       ĐƠN   
2      E04     2  20:45:00  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
3      E03     2  20:45:00  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
4      F04     1  19:30:00                   NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
...    ...   ...       ...                                      ...       ...   
35469  B10     4  21:35:00  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
35470  B09     4  21:35:00  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
35471  B07     4  21:35:00  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
35472  C14     4  19:15:00                        AVENGERS: HỒI KẾT       ĐƠN   
35473  C13     4  19:15:00                        AVENGERS: HỒI KẾT       ĐƠN   

         saledate  
0      2019-05-06  
1      2019-05-06  
2      2019-05-22  
3      2019-05-22  
4      2019-05-30  
...           ...  
35469  2019-05-30  
35470  2019-05-30  
35471  2019-05-30  
35472  2019-05-08  
35473  2019-05-08  

[33263 rows x 6 columns]

In [279]:
# Lọc những dòng có 'ticket price' bằng 45000
filtered_tickets_45 = tickets[tickets['ticket price'] == 45000]

# Lấy giá trị duy nhất của 'slot' và 'room' từ những dòng đã lọc
unique_slots = filtered_tickets_45['slot'].unique()
unique_rooms = filtered_tickets_45['room'].unique()
unique_film=filtered_tickets_45['film'].unique()
unique_slot_type=filtered_tickets_45['slot type'].unique()
(unique_slots, unique_rooms,unique_film,unique_slot_type)

(array(['G04', 'G03', 'E04', 'E03', 'F04', 'F03', 'E11', 'E10', 'F14',
        'F15', 'H03', 'H04', 'E09', 'D10', 'D09', 'G09', 'G08', 'G07',
        'G10', 'I13', 'I12', 'H10', 'H09', 'K07', 'K06', 'E07', 'E08',
        'F06', 'F05', 'I06', 'I04', 'I05', 'D03', 'D02', 'D01', 'E12',
        'H15', 'H16', 'H02', 'H01', 'A08', 'A10', 'E01', 'A09', 'A12',
        'A11', 'F01', 'I11', 'I10', 'F07', 'F08', 'I14', 'I15', 'I08',
        'I07', 'I09', 'H13', 'H11', 'H12', 'F10', 'F09', 'E06', 'B13',
        'I02', 'I01', 'H08', 'H05', 'H14', 'E16', 'E15', 'E17', 'H17',
        'G16', 'G15', 'G17', 'G02', 'G01', 'J10', 'J09', 'J11', 'E13',
        'B04', 'B03', 'G11', 'G12', 'F12', 'F11', 'E02', 'B07', 'B06',
        'G13', 'I16', 'K09', 'K10', 'C11', 'G14', 'J12', 'J13', 'J14',
        'J15', 'D08', 'G05', 'G06', 'D11', 'F13', 'H06', 'D13', 'D15',
        'D14', 'D06', 'D07', 'E05', 'D12', 'J08', 'J07', 'K02', 'K01',
        'E14', 'F02', 'A13', 'B16', 'B15', 'D05', 'I03', 'F16', 'K11',
      

#### Khi giá vé là 90000

In [280]:
selection = tickets[tickets['ticket price'] == 90000][['slot', 'room','time','film','slot type','saledate']]
selection

slot  room      time                              film slot type  \
18     H09     2  20:20:00            NGÔI ĐỀN KỲ QUÁI (C18)       ĐÔI   
22     J04     1  22:30:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
31     J05     1  12:40:00            NGÔI ĐỀN KỲ QUÁI (C18)       ĐÔI   
34     H03     2  16:40:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
111    H05     2  12:10:00                 VÔ GIAN ĐẠO (C18)       ĐÔI   
...    ...   ...       ...                               ...       ...   
35431  H02     2  13:05:00             LẬT MẶT: NHÀ CÓ KHÁCH       ĐÔI   
35432  J05     1  09:20:00    POKÉMON: THÁM TỬ PIKACHU (C13)       ĐÔI   
35433  J09     1  20:40:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
35461  J08     1  20:00:00                  ALADDIN (LT) (G)       ĐÔI   
35465  H03     2  22:25:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   

         saledate  
18     2019-05-28  
22     2019-05-15  
31     2019-05-30  
34     2019-05-10  
111    2019-05-24  
...           ...  
35431  2019-05-06  
35432  2019-05-17  
35433  2019-05-16  
35461  2019-05-23  
35465  2019-05-09  

[1383 rows x 6 columns]

In [281]:
# Lọc những dòng có 'ticket price' bằng 90000
filtered_tickets_90 = tickets[tickets['ticket price'] == 90000]

# Lấy giá trị duy nhất của 'slot' và 'room' từ những dòng đã lọc
unique_slots = filtered_tickets_90['slot'].unique()
unique_rooms = filtered_tickets_90['room'].unique()
unique_film=filtered_tickets_90['film'].unique()
unique_slot_type=filtered_tickets_90['slot type'].unique()
(unique_slots, unique_rooms,unique_film,unique_slot_type)

(array(['H09', 'J04', 'J05', 'H03', 'H05', 'H06', 'J07', 'J06', 'J03',
        'J02', 'H07', 'H04', 'J01', 'J08', 'H02', 'H08', 'J09', 'H01'],
       dtype=object),
 array([2, 1], dtype=int64),
 array(['NGÔI ĐỀN KỲ QUÁI (C18)', 'MẸ MA THAN KHÓC LA LLORONA (C18)',
        'VÔ GIAN ĐẠO (C18)', 'ƯỚC HẸN MÙA THU',
        'POKÉMON: THÁM TỬ PIKACHU (C13)', 'AVENGERS: HỒI KẾT',
        'CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)', 'THẰNG EM LÝ TƯỞNG',
        'LẬT MẶT: NHÀ CÓ KHÁCH', 'ALADDIN (LT) (G)',
        '(LT) DORAEMON: NOBITA VÀ MẶT TRĂNG PHIÊU LƯU KÝ (G)',
        'ALADDIN (PD) (G)', 'JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)',
        'VỢ BA', 'NỤ HÔN MA QUÁI (C18)', 'QUÝ CÔ LỪA ĐẢO'], dtype=object),
 array(['ĐÔI'], dtype=object))

#### =>> Có 1 nhận xét là giá vé đơn vào các ngày thường sẽ là 45000 và giá vé đôi sẽ 90000. Hai giá vé này là áp dụng cho ngày bình thường, không phải dịp lễ. Đồng thời , các vé đơn được áp dụng cho mọi phòng chiếu , tức là cả 4 phòng chiếu , tuy nhiên vé đôi chỉ là áp dụng cho 2 phòng chiếu phim là phòng số 1 và phòng số 2. Đồng thời giá vé đôi chỉ áp dụng cho các vé vip , ví dụ như là các ghê ở hàng H và hàng J

#### Khi giá vé là 75000

In [282]:
selection = tickets[tickets['ticket price'] == 75000][['slot', 'room','time','film','slot type','saledate']]
selection

slot  room      time               film slot type    saledate
1189   D16     4  20:00:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
1190   D15     4  20:00:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
1800   E10     2  07:30:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
1973   G14     1  18:30:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
1974   G15     1  18:30:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
...    ...   ...       ...                ...       ...         ...
35148  J02     4  10:15:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
35149  J01     4  10:15:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
35150  H16     3  16:00:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
35398  F12     3  12:30:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01
35399  F13     3  12:30:00  AVENGERS: HỒI KẾT       ĐƠN  2019-05-01

[799 rows x 6 columns]

In [283]:
# Lọc những dòng có 'ticket price' bằng 75000
filtered_tickets_75 = tickets[tickets['ticket price'] == 75000]

# Lấy giá trị duy nhất của 'slot' và 'room' từ những dòng đã lọc
unique_slots = filtered_tickets_75['slot'].unique()
unique_rooms = filtered_tickets_75['room'].unique()
unique_film=filtered_tickets_75['film'].unique()
unique_slot_type=filtered_tickets_75['slot type'].unique()
(unique_slots, unique_rooms,unique_film,unique_slot_type)

(array(['D16', 'D15', 'E10', 'G14', 'G15', 'C12', 'C13', 'C14', 'K11',
        'K12', 'C11', 'C15', 'G07', 'G08', 'G06', 'I15', 'I16', 'I04',
        'I03', 'H01', 'H02', 'B01', 'I13', 'I12', 'I06', 'I05', 'K19',
        'K18', 'F01', 'F02', 'E01', 'I11', 'E03', 'F03', 'E02', 'E04',
        'E05', 'E06', 'E09', 'E08', 'E07', 'K08', 'K09', 'K07', 'K10',
        'E17', 'E16', 'D03', 'D02', 'D01', 'F04', 'E11', 'D05', 'G01',
        'E12', 'D06', 'D04', 'D11', 'D12', 'D14', 'D17', 'D13', 'H07',
        'B14', 'B13', 'H08', 'E15', 'F10', 'F11', 'F07', 'F08', 'F09',
        'C16', 'C17', 'G05', 'A13', 'A14', 'B16', 'B17', 'F15', 'F14',
        'F16', 'F17', 'H06', 'G16', 'G17', 'C04', 'C03', 'D10', 'D07',
        'C06', 'C05', 'J03', 'J04', 'F12', 'K02', 'B10', 'B09', 'H11',
        'H12', 'E13', 'E14', 'F06', 'F05', 'D09', 'G04', 'G03', 'K06',
        'I14', 'K05', 'H15', 'H16', 'C09', 'C08', 'C10', 'C07', 'D08',
        'H03', 'H04', 'H05', 'C02', 'C01', 'B02', 'H09', 'H10', 'I08',
      

#### Khi giá vé là 160000

In [284]:
selection = tickets[tickets['ticket price'] == 160000][['slot', 'room','time','film','slot type','saledate']]
selection

slot  room      time                              film slot type  \
1799   H05     2  07:30:00                 AVENGERS: HỒI KẾT       ĐÔI   
11520  H07     2  14:05:00                 AVENGERS: HỒI KẾT       ĐÔI   
11525  J04     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
16977  H09     2  14:05:00                 AVENGERS: HỒI KẾT       ĐÔI   
24280  J08     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
24281  J09     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
24288  J01     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
32322  J07     1  08:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
32343  J06     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
32344  J07     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
32359  J02     1  08:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
32360  H06     2  14:05:00                 AVENGERS: HỒI KẾT       ĐÔI   
32432  H04     2  17:20:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
32476  J06     1  08:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
32477  J03     1  08:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
32495  J09     1  15:15:00                 AVENGERS: HỒI KẾT       ĐÔI   
32517  J08     1  21:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
32616  H02     2  17:20:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
32628  J05     1  12:00:00                 AVENGERS: HỒI KẾT       ĐÔI   
32643  J02     1  15:15:00                 AVENGERS: HỒI KẾT       ĐÔI   
34025  J09     1  21:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
34034  H01     2  21:05:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
34075  H02     2  21:05:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
34103  H06     2  07:30:00                 AVENGERS: HỒI KẾT       ĐÔI   
34111  H04     2  10:45:00                 AVENGERS: HỒI KẾT       ĐÔI   
34114  J06     1  15:15:00                 AVENGERS: HỒI KẾT       ĐÔI   
34115  H07     2  17:20:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   
34160  H05     2  23:00:00  MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI   

         saledate  
1799   2019-05-01  
11520  2019-05-01  
11525  2019-05-01  
16977  2019-05-01  
24280  2019-05-01  
24281  2019-05-01  
24288  2019-05-01  
32322  2019-05-01  
32343  2019-05-01  
32344  2019-05-01  
32359  2019-05-01  
32360  2019-05-01  
32432  2019-05-01  
32476  2019-05-01  
32477  2019-05-01  
32495  2019-05-01  
32517  2019-05-01  
32616  2019-05-01  
32628  2019-05-01  
32643  2019-05-01  
34025  2019-05-01  
34034  2019-05-01  
34075  2019-05-01  
34103  2019-05-01  
34111  2019-05-01  
34114  2019-05-01  
34115  2019-05-01  
34160  2019-05-01

In [285]:
# Lọc những dòng có 'ticket price' bằng 160000
filtered_tickets_160 = tickets[tickets['ticket price'] == 160000]

# Lấy giá trị duy nhất của 'slot' và 'room' từ những dòng đã lọc
unique_slots = filtered_tickets_160['slot'].unique()
unique_rooms = filtered_tickets_160['room'].unique()
unique_film=filtered_tickets_160['film'].unique()
unique_slot_type=filtered_tickets_160['slot type'].unique()
(unique_slots, unique_rooms,unique_film,unique_slot_type)

(array(['H05', 'H07', 'J04', 'H09', 'J08', 'J09', 'J01', 'J07', 'J06',
        'J02', 'H06', 'H04', 'J03', 'H02', 'J05', 'H01'], dtype=object),
 array([2, 1], dtype=int64),
 array(['AVENGERS: HỒI KẾT', 'MẸ MA THAN KHÓC LA LLORONA (C18)'],
       dtype=object),
 array(['ĐÔI'], dtype=object))

#### =>> Nhận xét : Vào dịp lễ ( ngày quốc khánh ngày 1/5/2019) thì giá vé có sự tăng lên, cụ thể là giá vé đơn là 75000 và giá vé đôi là 160000. Cũng như những ngày bình thường thì phòng vé áp dụng được ghế đôi là phòng 1 và phòng 2 . Vào ngày lễ thì chỉ chiếu 2 phim là Avenger và Me ma than khóc là được xem vào dịp lễ 

#### Kiểm tra giá vé bằng 0 

In [286]:
selection = tickets[tickets['ticket price'] == 0][['slot', 'room','time','film','slot type','saledate','orderid']]
selection

slot  room      time                    film slot type    saledate  \
7327  D11     4  17:25:00  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN  2019-05-26   

               orderid  
7327  10126052019B0123

=>>> Kiểm tra thử customerid kèm theo là film và slot type

In [287]:
tickets.loc[tickets['ticket price'] == 0, 'customerid']

7327    0000029127
Name: customerid, dtype: object

In [288]:
tickets[tickets['customerid'] == '0000029127']

orderid cashier    saledate     total  customerid  ticketcode  \
2464  10102052019B0049  emp011  2019-05-02   45000.0  0000029127    20071445   
2465  10102052019B0081  emp011  2019-05-02   90000.0  0000029127    20071650   
2466  10102052019B0081  emp011  2019-05-02   90000.0  0000029127    20071651   
2467  10102052019B0097  emp011  2019-05-02   90000.0  0000029127    20071757   
2468  10102052019B0097  emp011  2019-05-02   90000.0  0000029127    20071758   
...                ...     ...         ...       ...         ...         ...   
9564  10131052019B0255  emp011  2019-05-31  180000.0  0000029127    20108849   
9565  10131052019B0028  emp011  2019-05-31   90000.0  0000029127    20107816   
9566  10131052019B0028  emp011  2019-05-31   90000.0  0000029127    20107817   
9567  10131052019B0031  emp011  2019-05-31   45000.0  0000029127    20107834   
9568  10131052019B0056  emp004  2019-05-31   90000.0  0000029127    20107967   

           date      time slot  room                                     film  \
2464 2019-05-02  18:15:00  B17     3                        AVENGERS: HỒI KẾT   
2465 2019-05-02  20:20:00  A05     2                        AVENGERS: HỒI KẾT   
2466 2019-05-02  20:20:00  A06     2                        AVENGERS: HỒI KẾT   
2467 2019-05-02  21:30:00  B14     3                        AVENGERS: HỒI KẾT   
2468 2019-05-02  21:30:00  B15     3                        AVENGERS: HỒI KẾT   
...         ...       ...  ...   ...                                      ...   
9564 2019-05-31  23:00:00  D04     2  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)   
9565 2019-05-31  15:45:00  F12     2                     NỤ HÔN MA QUÁI (C18)   
9566 2019-05-31  15:45:00  F13     2                     NỤ HÔN MA QUÁI (C18)   
9567 2019-05-31  15:45:00  D12     2                     NỤ HÔN MA QUÁI (C18)   
9568 2019-05-31  18:00:00  G07     2                         ALADDIN (LT) (G)   

     slot type ticket type  ticket price popcorn  saletime  
2464       ĐƠN  Thành viên         45000   Không  18:19:25  
2465       ĐƠN  Thành viên         45000   Không  19:50:20  
2466       ĐƠN  Thành viên         45000   Không  19:50:20  
2467       ĐƠN  Thành viên         45000   Không  20:53:13  
2468       ĐƠN  Thành viên         45000   Không  20:53:13  
...        ...         ...           ...     ...       ...  
9564       ĐƠN  Thành viên         45000   Không  22:39:18  
9565       ĐƠN  Thành viên         45000   Không  15:37:55  
9566       ĐƠN  Thành viên         45000   Không  15:37:55  
9567       ĐƠN  Thành viên         45000   Không  15:42:53  
9568       ĐƠN  Thành viên         45000   Không  16:48:07  

[7105 rows x 16 columns]

In ra records mà customerid , slot type , file và date 

In [289]:
filtered_tickets = tickets[
    (tickets['customerid'] == '0000029127') &
    (tickets['film'] == 'NGÔI ĐỀN KỲ QUÁI (C18)') &
    (tickets['slot type'] == 'ĐƠN') &
    (tickets['saledate'] == '2019-05-26') &
    (tickets['room'] == 4) &
    (tickets['orderid']=='10126052019B0123')
]

# In ra các bản ghi sau khi lọc
filtered_tickets


orderid cashier    saledate    total  customerid  ticketcode  \
7321  10126052019B0123  emp010  2019-05-26  90000.0  0000029127    20102170   
7326  10126052019B0123  emp010  2019-05-26  90000.0  0000029127    20102168   
7327  10126052019B0123  emp010  2019-05-26  90000.0  0000029127    20102169   

           date      time slot  room                    film slot type  \
7321 2019-05-26  17:25:00  D12     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
7326 2019-05-26  17:25:00  D10     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
7327 2019-05-26  17:25:00  D11     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   

     ticket type  ticket price popcorn  saletime  
7321  Thành viên         45000      Có  17:15:50  
7326  Thành viên         45000      Có  17:15:50  
7327  Thành viên             0      Có  17:15:50

=>> Dựa vào kết quả tìm kiếm , ta có thể chỉnh lại ticketprice từ 0 thành 45 (do giá vé là giá vé đơn và cũng là chiếu trong ngày thường). Việc chỉnh sửa này có thể dựa vào một số yếu tố như là loại vé ( slot type ) là loại vé Đơn , đồng thờ cashier cũng không phải website, ngày chiếu cũng không phải là ngày quốc lễ

In [290]:
tickets['ticket price'] = tickets['ticket price'].replace(0, 45000)

Kiểm tra lại

In [291]:
filtered_tickets = tickets[
    (tickets['customerid'] == '0000029127') &
    (tickets['film'] == 'NGÔI ĐỀN KỲ QUÁI (C18)') &
    (tickets['slot type'] == 'ĐƠN') &
    (tickets['saledate'] == '2019-05-26') &
    (tickets['room'] == 4) &
    (tickets['orderid']=='10126052019B0123')
]

# In ra các bản ghi sau khi lọc
filtered_tickets

orderid cashier    saledate    total  customerid  ticketcode  \
7321  10126052019B0123  emp010  2019-05-26  90000.0  0000029127    20102170   
7326  10126052019B0123  emp010  2019-05-26  90000.0  0000029127    20102168   
7327  10126052019B0123  emp010  2019-05-26  90000.0  0000029127    20102169   

           date      time slot  room                    film slot type  \
7321 2019-05-26  17:25:00  D12     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
7326 2019-05-26  17:25:00  D10     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
7327 2019-05-26  17:25:00  D11     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   

     ticket type  ticket price popcorn  saletime  
7321  Thành viên         45000      Có  17:15:50  
7326  Thành viên         45000      Có  17:15:50  
7327  Thành viên         45000      Có  17:15:50

=>> đã chỉnh thành công , nhận ra là total có bị sai sót =>> phải xử lý cột total

## Làm việc với ticketcode

In [292]:
print(tickets["ticketcode"].dtype)

int64


In [293]:
tickets["ticketcode"].isnull().values.any()

False

==>> Không có null tại cột ticketcode

In [294]:
# Lấy các giá trị trùng lặp của cột ticketcode 
ticketcode_dupe = tickets['ticketcode'].duplicated(keep=False)

# In ra các giá trị trùng lặp
tickets.loc[ticketcode_dupe].head()

orderid  cashier    saledate    total  customerid  ticketcode  \
16817             WEB27  Website  2019-05-15      NaN  0001122882    20088849   
23096  12515052019B0048   emp007  2019-05-15  90000.0  0003008604    20088849   

            date      time slot  room  \
16817 2019-05-15  21:40:00  F12     3   
23096 2019-05-15  21:40:00  H13     3   

                                          film slot type ticket type  \
16817  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
23096  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   

       ticket price                   popcorn  saletime  
16817         45000  Website/Liên hệ tại quầy       NaT  
23096         45000                     Không  21:33:51

==>> thì cứ theo thứ tự vì cái customerid 0001122882 được nhập trước =>> nên là phải thay đổi cái sau 

In [295]:
# Thay thế 'ticketcode' cụ thể cho 'customerid' và 'ticketcode' cụ thể
tickets.loc[(tickets['customerid'] == '0003008604') & (tickets['ticketcode'] == 20088849), 'ticketcode'] = '20000000'

In [296]:
# Kiểm tra lại DataFrame để xác nhận sự thay đổi
tickets[tickets['customerid'] == '0003008604']

orderid cashier    saledate    total  customerid ticketcode  \
23095  10006052019B0338  emp007  2019-05-06  90000.0  0003008604   20075611   
23096  12515052019B0048  emp007  2019-05-15  90000.0  0003008604   20000000   
23097  12515052019B0048  emp007  2019-05-15  90000.0  0003008604   20088850   
23098  10123052019B0090  emp004  2019-05-23  90000.0  0003008604   20098166   
23099  10123052019B0090  emp004  2019-05-23  90000.0  0003008604   20098165   
23100  12525052019B0018  emp012  2019-05-25  90000.0  0003008604   20100894   
23101  12525052019B0018  emp012  2019-05-25  90000.0  0003008604   20100892   

            date      time slot  room  \
23095 2019-05-06  22:05:00  H07     2   
23096 2019-05-15  21:40:00  H13     3   
23097 2019-05-15  21:40:00  H14     3   
23098 2019-05-23  21:35:00  J10     4   
23099 2019-05-23  21:35:00  J09     4   
23100 2019-05-25  21:40:00  I08     4   
23101 2019-05-25  21:40:00  I07     4   

                                          film slot type ticket type  \
23095         MẸ MA THAN KHÓC LA LLORONA (C18)       ĐÔI  Thành viên   
23096  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
23097  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
23098                         ALADDIN (LT) (G)       ĐƠN  Thành viên   
23099                         ALADDIN (LT) (G)       ĐƠN  Thành viên   
23100                   NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN  Thành viên   
23101                   NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN  Thành viên   

       ticket price popcorn  saletime  
23095         90000   Không  21:47:30  
23096         45000   Không  21:33:51  
23097         45000   Không  21:33:51  
23098         45000   Không  21:15:35  
23099         45000   Không  21:15:35  
23100         45000   Không  19:55:21  
23101         45000   Không  19:55:21

## Làm việc với cột saletime

In [297]:
print(tickets["saletime"].dtype)

object


In [298]:
tickets["saletime"].isnull().values.any()

True

=>> Có missing tại chỗ saletime ( là trường hợp cashier là website)

In [299]:
# Gán giá trị saletime thành Không xác định rõ 
tickets['saletime'].fillna('Không xác định rõ', inplace=True)

In [300]:
tickets["saletime"].isnull().values.any()

False

In [301]:
salrtime_values = tickets['saletime'].value_counts()
salrtime_values

saletime
Không xác định rõ    96
18:11:38             46
14:14:16             32
13:07:42             28
19:07:58             27
                     ..
22:34:16              1
08:36:25              1
19:44:14              1
19:42:10              1
20:07:02              1
Name: count, Length: 12450, dtype: int64

=>> Đã xử lý missing value thành công

## Làm việc với cột total

In [302]:
# Lọc ra các bản ghi mà cột 'total' mang giá trị null
null_total_records = tickets[tickets['total'].isnull()]

# In ra các bản ghi đó
null_total_records

orderid  cashier    saledate  total  customerid ticketcode       date  \
23      WEB01  Website  2019-05-25    NaN  0000000228   20100926 2019-05-25   
24      WEB01  Website  2019-05-25    NaN  0000000228   20100927 2019-05-25   
580     WEB02  Website  2019-05-18    NaN  0000011318   20092413 2019-05-18   
581     WEB02  Website  2019-05-18    NaN  0000011318   20092412 2019-05-18   
582     WEB02  Website  2019-05-18    NaN  0000011318   20092411 2019-05-18   
...       ...      ...         ...    ...         ...        ...        ...   
23102   WEB43  Website  2019-05-30    NaN  0003008617   20106999 2019-05-30   
23103   WEB43  Website  2019-05-30    NaN  0003008617   20106998 2019-05-30   
23106   WEB42  Website  2019-05-17    NaN  0003008617   20091106 2019-05-17   
23107   WEB42  Website  2019-05-17    NaN  0003008617   20091105 2019-05-17   
23108   WEB42  Website  2019-05-17    NaN  0003008617   20091107 2019-05-17   

           time slot  room                                     film slot type  \
23     19:45:00  G09     3                         ALADDIN (PD) (G)       ĐƠN   
24     19:45:00  G10     3                         ALADDIN (PD) (G)       ĐƠN   
580    18:40:00  G09     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
581    18:40:00  G08     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
582    18:40:00  G07     1           POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN   
...         ...  ...   ...                                      ...       ...   
23102  21:35:00  H09     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23103  21:35:00  H08     4  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN   
23106  20:15:00  F14     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23107  20:15:00  F13     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   
23108  20:15:00  F15     2  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN   

      ticket type  ticket price                   popcorn           saletime  
23     Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
24     Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
580    Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
581    Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
582    Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
...           ...           ...                       ...                ...  
23102  Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23103  Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23106  Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23107  Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23108  Thành viên         45000  Website/Liên hệ tại quầy  Không xác định rõ  

[96 rows x 16 columns]

In [303]:

# Tính tổng ticket price cho mỗi sự kết hợp của customerid và saledate
grouped = tickets.groupby(['customerid', 'saledate'])['ticket price'].sum()

# Cập nhật giá trị total cho những bản ghi có total là null
# Sử dụng idx để lưu vị trí của các dòng cần cập nhật
idx = tickets['total'].isnull()
# Cập nhật giá trị total sử dụng map trên các dòng đã lọc
tickets.loc[idx, 'total'] = tickets[idx].apply(lambda row: grouped.get((row['customerid'], row['saledate'])), axis=1)


In [304]:
tickets[tickets["cashier"] == "Website"]

orderid  cashier    saledate     total  customerid ticketcode  \
23      WEB01  Website  2019-05-25   90000.0  0000000228   20100926   
24      WEB01  Website  2019-05-25   90000.0  0000000228   20100927   
580     WEB02  Website  2019-05-18  135000.0  0000011318   20092413   
581     WEB02  Website  2019-05-18  135000.0  0000011318   20092412   
582     WEB02  Website  2019-05-18  135000.0  0000011318   20092411   
...       ...      ...         ...       ...         ...        ...   
23102   WEB43  Website  2019-05-30   90000.0  0003008617   20106999   
23103   WEB43  Website  2019-05-30   90000.0  0003008617   20106998   
23106   WEB42  Website  2019-05-17  135000.0  0003008617   20091106   
23107   WEB42  Website  2019-05-17  135000.0  0003008617   20091105   
23108   WEB42  Website  2019-05-17  135000.0  0003008617   20091107   

            date      time slot  room  \
23    2019-05-25  19:45:00  G09     3   
24    2019-05-25  19:45:00  G10     3   
580   2019-05-18  18:40:00  G09     1   
581   2019-05-18  18:40:00  G08     1   
582   2019-05-18  18:40:00  G07     1   
...          ...       ...  ...   ...   
23102 2019-05-30  21:35:00  H09     4   
23103 2019-05-30  21:35:00  H08     4   
23106 2019-05-17  20:15:00  F14     2   
23107 2019-05-17  20:15:00  F13     2   
23108 2019-05-17  20:15:00  F15     2   

                                          film slot type ticket type  \
23                            ALADDIN (PD) (G)       ĐƠN  Thành viên   
24                            ALADDIN (PD) (G)       ĐƠN  Thành viên   
580             POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN  Thành viên   
581             POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN  Thành viên   
582             POKÉMON: THÁM TỬ PIKACHU (C13)       ĐƠN  Thành viên   
...                                        ...       ...         ...   
23102  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
23103  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
23106  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
23107  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
23108  JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   

       ticket price                   popcorn           saletime  
23            45000  Website/Liên hệ tại quầy  Không xác định rõ  
24            45000  Website/Liên hệ tại quầy  Không xác định rõ  
580           45000  Website/Liên hệ tại quầy  Không xác định rõ  
581           45000  Website/Liên hệ tại quầy  Không xác định rõ  
582           45000  Website/Liên hệ tại quầy  Không xác định rõ  
...             ...                       ...                ...  
23102         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23103         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23106         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23107         45000  Website/Liên hệ tại quầy  Không xác định rõ  
23108         45000  Website/Liên hệ tại quầy  Không xác định rõ  

[96 rows x 16 columns]

### Xử lý 3 cột total bị lỗi ở phía trên lúc xử lý ticket price =0

In [305]:
# Lọc các điều kiện
filtered_total = tickets[(tickets['customerid'] == '0000029127') & 
                          (tickets['film'] == 'NGÔI ĐỀN KỲ QUÁI (C18)') &
                          (tickets['slot type'] == 'ĐƠN') & 
                          (tickets['saledate'] == '2019-05-26') &
                          (tickets['room'] == 4) &  
                          (tickets['orderid']=='10126052019B0123')]

# Thay đổi giá trị cột 'total'                  
filtered_total['total'] = 135000

filtered_total

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_40928\3141983532.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_total['total'] = 135000


orderid cashier    saledate   total  customerid ticketcode  \
7321  10126052019B0123  emp010  2019-05-26  135000  0000029127   20102170   
7326  10126052019B0123  emp010  2019-05-26  135000  0000029127   20102168   
7327  10126052019B0123  emp010  2019-05-26  135000  0000029127   20102169   

           date      time slot  room                    film slot type  \
7321 2019-05-26  17:25:00  D12     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
7326 2019-05-26  17:25:00  D10     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   
7327 2019-05-26  17:25:00  D11     4  NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN   

     ticket type  ticket price popcorn  saletime  
7321  Thành viên         45000      Có  17:15:50  
7326  Thành viên         45000      Có  17:15:50  
7327  Thành viên         45000      Có  17:15:50

## Làm việc với cột Room

In [306]:
print(tickets["room"].dtype)

int64


In [307]:
room=tickets['room'].unique()
print(room)

[3 2 1 4]


In [308]:
tickets["room"].isnull().values.any()

False

In [309]:
room_counts = tickets["room"].value_counts()

print(room_counts)

room
4    9992
2    8822
3    8495
1    8165
Name: count, dtype: int64


=>> Các phòng chiếu cũng có số lượng chệnh lệch , cao nhất chính là Phòng chiếu số 4 và thấp nhất là Phòng chiếu số 1

## Tạo thêm cột mới =>> Cách thức mua vé ( Online hay Offline)

In [310]:
# Tạo cột mới 'Cách thức mua vé' dựa trên cột 'saletime'
tickets['Cách thức mua vé'] = np.where(tickets['saletime'] == 'Không xác định rõ', 'Online', 'Offline')


In [311]:
tickets

orderid cashier    saledate     total       customerid  \
0      10006052019B0225  emp002  2019-05-06   90000.0       0000000014   
1      10006052019B0225  emp002  2019-05-06   90000.0       0000000014   
2      10022052019B0167  emp011  2019-05-22   90000.0       0000000034   
3      10022052019B0167  emp011  2019-05-22   90000.0       0000000034   
4      10130052019B0141  emp005  2019-05-30   90000.0       0000000034   
...                 ...     ...         ...       ...              ...   
35469  10130052019B0192  emp005  2019-05-30  180000.0  WEBS00000044909   
35470  10130052019B0192  emp005  2019-05-30  180000.0  WEBS00000044909   
35471  10130052019B0192  emp005  2019-05-30  180000.0  WEBS00000044909   
35472  12508052019B0036  emp007  2019-05-08   90000.0  WEBS00000046015   
35473  12508052019B0036  emp007  2019-05-08   90000.0  WEBS00000046015   

      ticketcode       date      time slot  room  \
0       20074925 2019-05-06  18:15:00  G04     3   
1       20074924 2019-05-06  18:15:00  G03     3   
2       20097042 2019-05-22  20:45:00  E04     2   
3       20097041 2019-05-22  20:45:00  E03     2   
4       20106761 2019-05-30  19:30:00  F04     1   
...          ...        ...       ...  ...   ...   
35469   20107072 2019-05-30  21:35:00  B10     4   
35470   20107071 2019-05-30  21:35:00  B09     4   
35471   20107069 2019-05-30  21:35:00  B07     4   
35472   20077797 2019-05-08  19:15:00  C14     4   
35473   20077796 2019-05-08  19:15:00  C13     4   

                                          film slot type ticket type  \
0                            AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
1                            AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
2      JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
3      JOHN WICK 3: CHUẨN BỊ CHIẾN TRANH (C18)       ĐƠN  Thành viên   
4                       NGÔI ĐỀN KỲ QUÁI (C18)       ĐƠN  Thành viên   
...                                        ...       ...         ...   
35469  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35470  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35471  CHÚA TỂ GODZILLA: ĐẾ VƯƠNG BẤT TỬ (C13)       ĐƠN  Thành viên   
35472                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   
35473                        AVENGERS: HỒI KẾT       ĐƠN  Thành viên   

       ticket price popcorn  saletime Cách thức mua vé  
0             45000   Không  16:40:43          Offline  
1             45000   Không  16:40:43          Offline  
2             45000   Không  20:30:28          Offline  
3             45000   Không  20:30:28          Offline  
4             45000   Không  19:28:44          Offline  
...             ...     ...       ...              ...  
35469         45000   Không  21:49:46          Offline  
35470         45000   Không  21:49:46          Offline  
35471         45000   Không  21:49:46          Offline  
35472         45000   Không  19:26:47          Offline  
35473         45000   Không  19:26:47          Offline  

[35474 rows x 17 columns]

## Check missing value lần cuối 

In [312]:
tickets.isnull().any()

orderid             False
cashier             False
saledate            False
total               False
customerid          False
ticketcode          False
date                False
time                False
slot                False
room                False
film                False
slot type           False
ticket type         False
ticket price        False
popcorn             False
saletime            False
Cách thức mua vé    False
dtype: bool

# Đã hoàn toàn không còn missing value. Một số lưu ý sau khi phân tích về tickets :
    -- Orderid sẽ bị missing value tại trường hợp cashier mang giá trị website , tương tự với popcorn , total và saledate =>> Nên cân nhắc về trường hợp này, tuy nhiên trong trường hợp này thì nhóm sẽ lại đặt lại orderid
    -- Tương tự với total và saledate , nhóm cũng đã xử lý phù hợp với một số bất thường và missing value
    -- Với ticket code , nhóm đã thực hiện việc đưa ra được nhận xét về sự khác biệt giữa 4 mức giá và đã xử lý thành công mức giá bị sai
    -- Với cột popcorn , nhóm đã hoàn thành xử lý missing value và cũng đưa ra được nhận xét răng popcorn không hề ảnh hưởng đến doanh thu của rạp dựa vào bộ dữ liệu đã cung cấp ( tức là total sẽ dựa vào ticket price)
    -- Với ticket code , nhóm đã thực hiện việc xử lý bất thường của ticket code ( cụ thể ở đây là ticket code bị trùng )

## Xuất ra file excel

In [313]:
tickets.to_excel("Tickets.xlsx")